import { Cocktail } from "@/types";

export const cocktails: Cocktail[] = [
  // VODKA COCKTAILS
  {
    id: "1",
    slug: "moscow-mule",
    name: "Moscow Mule",
    description: "A refreshing vodka cocktail with ginger beer and lime, traditionally served in a copper mug.",
    image: "/cocktails/moscow-mule.jpg",
    ingredients: [
      { name: "Vodka", amount: "2", unit: "oz" },
      { name: "Ginger Beer", amount: "4", unit: "oz" },
      { name: "Lime Juice", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Fill a copper mug with ice",
      "Add vodka and lime juice",
      "Top with ginger beer",
      "Stir gently and garnish with lime wheel",
    ],
    glass: "Copper Mug",
    garnish: "Lime wheel",
    baseSpirit: "vodka",
    category: "classic",
    difficulty: 1,
    strength: 3,
    tags: ["refreshing", "ginger", "copper mug", "easy"],
    created_at: "2025-01-01",
  },
  {
    id: "2",
    slug: "cosmopolitan",
    name: "Cosmopolitan",
    description: "A sophisticated pink cocktail made famous by Sex and the City. Tart, sweet, and elegant.",
    image: "/cocktails/cosmopolitan.jpg",
    ingredients: [
      { name: "Vodka", amount: "1.5", unit: "oz" },
      { name: "Cointreau", amount: "0.75", unit: "oz" },
      { name: "Lime Juice", amount: "0.75", unit: "oz" },
      { name: "Cranberry Juice", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Add all ingredients to a shaker with ice",
      "Shake vigorously until well chilled",
      "Strain into a chilled martini glass",
      "Garnish with orange peel",
    ],
    glass: "Martini Glass",
    garnish: "Orange peel",
    baseSpirit: "vodka",
    category: "classic",
    difficulty: 2,
    strength: 4,
    tags: ["elegant", "pink", "citrus", "shaken"],
    created_at: "2025-01-01",
  },
  {
    id: "3",
    slug: "vodka-martini",
    name: "Vodka Martini",
    description: "The iconic James Bond drink. Clean, crisp, and sophisticated - shaken or stirred.",
    image: "/cocktails/vodka-martini.jpg",
    ingredients: [
      { name: "Vodka", amount: "2.5", unit: "oz" },
      { name: "Dry Vermouth", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Add vodka and vermouth to a mixing glass with ice",
      "Stir for 30 seconds until well chilled",
      "Strain into a chilled martini glass",
      "Garnish with olives or lemon twist",
    ],
    glass: "Martini Glass",
    garnish: "Olives or lemon twist",
    baseSpirit: "vodka",
    category: "classic",
    difficulty: 2,
    strength: 5,
    tags: ["elegant", "strong", "james bond", "stirred"],
    created_at: "2025-01-01",
  },
  {
    id: "4",
    slug: "bloody-mary",
    name: "Bloody Mary",
    description: "The ultimate brunch cocktail. Savory, spicy, and the perfect hangover cure.",
    image: "/cocktails/bloody-mary.jpg",
    ingredients: [
      { name: "Vodka", amount: "1.5", unit: "oz" },
      { name: "Tomato Juice", amount: "3", unit: "oz" },
      { name: "Lemon Juice", amount: "0.5", unit: "oz" },
      { name: "Worcestershire Sauce", amount: "2", unit: "dashes" },
      { name: "Hot Sauce", amount: "2", unit: "dashes" },
      { name: "Salt & Pepper", amount: "to taste" },
    ],
    instructions: [
      "Rim glass with celery salt (optional)",
      "Add all ingredients to a shaker with ice",
      "Roll gently between shaker tins (don't shake hard)",
      "Strain into an ice-filled highball glass",
      "Garnish elaborately with celery, olives, bacon, etc.",
    ],
    glass: "Highball Glass",
    garnish: "Celery stalk, olives, lemon",
    baseSpirit: "vodka",
    category: "classic",
    difficulty: 2,
    strength: 2,
    tags: ["brunch", "savory", "spicy", "hangover cure"],
    created_at: "2025-01-01",
  },
  {
    id: "5",
    slug: "screwdriver",
    name: "Screwdriver",
    description: "Simple, refreshing, and perfect for day drinking. Just vodka and OJ.",
    image: "/cocktails/screwdriver.jpg",
    ingredients: [
      { name: "Vodka", amount: "2", unit: "oz" },
      { name: "Orange Juice", amount: "4", unit: "oz" },
    ],
    instructions: [
      "Fill a highball glass with ice",
      "Add vodka",
      "Top with orange juice",
      "Stir and garnish with orange slice",
    ],
    glass: "Highball Glass",
    garnish: "Orange slice",
    baseSpirit: "vodka",
    category: "classic",
    difficulty: 1,
    strength: 2,
    tags: ["easy", "brunch", "refreshing", "citrus"],
    created_at: "2025-01-01",
  },
  {
    id: "6",
    slug: "espresso-martini",
    name: "Espresso Martini",
    description: "The perfect pick-me-up cocktail. Rich coffee flavor meets smooth vodka.",
    image: "/cocktails/espresso-martini.jpg",
    ingredients: [
      { name: "Vodka", amount: "2", unit: "oz" },
      { name: "Coffee Liqueur", amount: "0.5", unit: "oz" },
      { name: "Fresh Espresso", amount: "1", unit: "oz" },
      { name: "Simple Syrup", amount: "0.25", unit: "oz" },
    ],
    instructions: [
      "Add all ingredients to a shaker with ice",
      "Shake vigorously for 15 seconds",
      "Double strain into a chilled martini glass",
      "Garnish with three coffee beans",
    ],
    glass: "Martini Glass",
    garnish: "Three coffee beans",
    baseSpirit: "vodka",
    category: "classic",
    difficulty: 2,
    strength: 4,
    tags: ["coffee", "energizing", "after dinner", "shaken"],
    created_at: "2025-01-01",
  },

  // GIN COCKTAILS
  {
    id: "7",
    slug: "gin-and-tonic",
    name: "Gin & Tonic",
    description: "The quintessential British highball. Crisp, botanical, and utterly refreshing.",
    image: "/cocktails/gin-and-tonic.jpg",
    ingredients: [
      { name: "Gin", amount: "2", unit: "oz" },
      { name: "Tonic Water", amount: "4", unit: "oz" },
    ],
    instructions: [
      "Fill a highball glass with ice",
      "Add gin",
      "Top with tonic water",
      "Gently stir and garnish with lime",
    ],
    glass: "Highball Glass",
    garnish: "Lime wedge",
    baseSpirit: "gin",
    category: "classic",
    difficulty: 1,
    strength: 3,
    tags: ["refreshing", "british", "easy", "botanical"],
    created_at: "2025-01-01",
  },
  {
    id: "8",
    slug: "classic-martini",
    name: "Classic Martini",
    description: "The king of cocktails. Gin, vermouth, and a twist - nothing more, nothing less.",
    image: "/cocktails/classic-martini.jpg",
    ingredients: [
      { name: "Gin", amount: "2.5", unit: "oz" },
      { name: "Dry Vermouth", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Add gin and vermouth to a mixing glass with ice",
      "Stir for 30 seconds until well chilled",
      "Strain into a chilled martini glass",
      "Garnish with lemon twist or olive",
    ],
    glass: "Martini Glass",
    garnish: "Lemon twist or olive",
    baseSpirit: "gin",
    category: "classic",
    difficulty: 2,
    strength: 5,
    tags: ["elegant", "strong", "classic", "stirred"],
    created_at: "2025-01-01",
  },
  {
    id: "9",
    slug: "negroni",
    name: "Negroni",
    description: "A perfectly balanced Italian aperitif. Bitter, sweet, and boozy in equal measure.",
    image: "/cocktails/negroni.jpg",
    ingredients: [
      { name: "Gin", amount: "1", unit: "oz" },
      { name: "Campari", amount: "1", unit: "oz" },
      { name: "Sweet Vermouth", amount: "1", unit: "oz" },
    ],
    instructions: [
      "Add all ingredients to a rocks glass with ice",
      "Stir until well chilled",
      "Garnish with orange peel",
    ],
    glass: "Rocks Glass",
    garnish: "Orange peel",
    baseSpirit: "gin",
    category: "classic",
    difficulty: 1,
    strength: 4,
    tags: ["bitter", "italian", "aperitif", "stirred"],
    created_at: "2025-01-01",
  },
  {
    id: "10",
    slug: "tom-collins",
    name: "Tom Collins",
    description: "A refreshing gin sour topped with soda. Light, citrusy, and perfect for summer.",
    image: "/cocktails/tom-collins.jpg",
    ingredients: [
      { name: "Gin", amount: "2", unit: "oz" },
      { name: "Lemon Juice", amount: "1", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
      { name: "Club Soda", amount: "2", unit: "oz" },
    ],
    instructions: [
      "Add gin, lemon juice, and syrup to a shaker with ice",
      "Shake well",
      "Strain into an ice-filled Collins glass",
      "Top with club soda and garnish",
    ],
    glass: "Collins Glass",
    garnish: "Lemon wheel, cherry",
    baseSpirit: "gin",
    category: "classic",
    difficulty: 1,
    strength: 3,
    tags: ["refreshing", "citrus", "summer", "fizzy"],
    created_at: "2025-01-01",
  },
  {
    id: "11",
    slug: "french-75",
    name: "French 75",
    description: "Elegant gin and champagne cocktail. Named after a WWI artillery gun for its kick.",
    image: "/cocktails/french-75.jpg",
    ingredients: [
      { name: "Gin", amount: "1.5", unit: "oz" },
      { name: "Lemon Juice", amount: "0.75", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
      { name: "Champagne", amount: "2", unit: "oz" },
    ],
    instructions: [
      "Shake gin, lemon juice, and syrup with ice",
      "Strain into a champagne flute",
      "Top with champagne",
      "Garnish with lemon twist",
    ],
    glass: "Champagne Flute",
    garnish: "Lemon twist",
    baseSpirit: "gin",
    category: "classic",
    difficulty: 2,
    strength: 4,
    tags: ["elegant", "champagne", "celebration", "citrus"],
    created_at: "2025-01-01",
  },

  // RUM COCKTAILS
  {
    id: "12",
    slug: "mojito",
    name: "Mojito",
    description: "Cuba's gift to cocktails. Fresh mint, lime, rum, and soda - pure refreshment.",
    image: "/cocktails/mojito.jpg",
    ingredients: [
      { name: "White Rum", amount: "2", unit: "oz" },
      { name: "Fresh Mint", amount: "8-10", unit: "leaves" },
      { name: "Lime Juice", amount: "1", unit: "oz" },
      { name: "Simple Syrup", amount: "0.75", unit: "oz" },
      { name: "Club Soda", amount: "2", unit: "oz" },
    ],
    instructions: [
      "Gently muddle mint with lime juice and syrup",
      "Add rum and ice",
      "Top with club soda",
      "Stir gently and garnish with mint sprig",
    ],
    glass: "Highball Glass",
    garnish: "Mint sprig, lime wheel",
    baseSpirit: "rum",
    category: "tropical",
    difficulty: 2,
    strength: 3,
    tags: ["refreshing", "mint", "cuban", "summer"],
    created_at: "2025-01-01",
  },
  {
    id: "13",
    slug: "daiquiri",
    name: "Daiquiri",
    description: "The original rum sour. Simple, balanced, and dangerously drinkable.",
    image: "/cocktails/daiquiri.jpg",
    ingredients: [
      { name: "White Rum", amount: "2", unit: "oz" },
      { name: "Lime Juice", amount: "1", unit: "oz" },
      { name: "Simple Syrup", amount: "0.75", unit: "oz" },
    ],
    instructions: [
      "Add all ingredients to a shaker with ice",
      "Shake vigorously until well chilled",
      "Double strain into a chilled coupe glass",
    ],
    glass: "Coupe Glass",
    garnish: "Lime wheel",
    baseSpirit: "rum",
    category: "classic",
    difficulty: 1,
    strength: 4,
    tags: ["citrus", "simple", "cuban", "shaken"],
    created_at: "2025-01-01",
  },
  {
    id: "14",
    slug: "pina-colada",
    name: "Pina Colada",
    description: "Tropical paradise in a glass. Creamy coconut and pineapple with rum.",
    image: "/cocktails/pina-colada.jpg",
    ingredients: [
      { name: "White Rum", amount: "2", unit: "oz" },
      { name: "Coconut Cream", amount: "2", unit: "oz" },
      { name: "Pineapple Juice", amount: "3", unit: "oz" },
    ],
    instructions: [
      "Add all ingredients to a blender with ice",
      "Blend until smooth",
      "Pour into a hurricane glass",
      "Garnish with pineapple and cherry",
    ],
    glass: "Hurricane Glass",
    garnish: "Pineapple wedge, cherry",
    baseSpirit: "rum",
    category: "tropical",
    difficulty: 1,
    strength: 3,
    tags: ["tropical", "creamy", "blended", "vacation"],
    created_at: "2025-01-01",
  },
  {
    id: "15",
    slug: "dark-n-stormy",
    name: "Dark 'n' Stormy",
    description: "Dark rum meets spicy ginger beer. A Bermuda classic with serious depth.",
    image: "/cocktails/dark-n-stormy.jpg",
    ingredients: [
      { name: "Dark Rum", amount: "2", unit: "oz" },
      { name: "Ginger Beer", amount: "4", unit: "oz" },
      { name: "Lime Juice", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Fill a highball glass with ice",
      "Add lime juice and ginger beer",
      "Float dark rum on top",
      "Garnish with lime wheel",
    ],
    glass: "Highball Glass",
    garnish: "Lime wheel",
    baseSpirit: "rum",
    category: "classic",
    difficulty: 1,
    strength: 3,
    tags: ["ginger", "bermuda", "spicy", "easy"],
    created_at: "2025-01-01",
  },
  {
    id: "16",
    slug: "mai-tai",
    name: "Mai Tai",
    description: "The ultimate tiki cocktail. Complex, tropical, and perfect for luau vibes.",
    image: "/cocktails/mai-tai.jpg",
    ingredients: [
      { name: "White Rum", amount: "1", unit: "oz" },
      { name: "Dark Rum", amount: "1", unit: "oz" },
      { name: "Orange Curacao", amount: "0.5", unit: "oz" },
      { name: "Lime Juice", amount: "1", unit: "oz" },
      { name: "Orgeat Syrup", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Shake all ingredients except dark rum with ice",
      "Strain into an ice-filled rocks glass",
      "Float dark rum on top",
      "Garnish with mint and lime",
    ],
    glass: "Rocks Glass",
    garnish: "Mint sprig, lime wheel",
    baseSpirit: "rum",
    category: "tropical",
    difficulty: 3,
    strength: 4,
    tags: ["tiki", "tropical", "complex", "party"],
    created_at: "2025-01-01",
  },
  {
    id: "17",
    slug: "cuba-libre",
    name: "Cuba Libre",
    description: "Rum and coke elevated with fresh lime. Simple but satisfying.",
    image: "/cocktails/cuba-libre.jpg",
    ingredients: [
      { name: "White Rum", amount: "2", unit: "oz" },
      { name: "Cola", amount: "4", unit: "oz" },
      { name: "Lime Juice", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Fill a highball glass with ice",
      "Add rum and lime juice",
      "Top with cola",
      "Stir and garnish with lime wedge",
    ],
    glass: "Highball Glass",
    garnish: "Lime wedge",
    baseSpirit: "rum",
    category: "classic",
    difficulty: 1,
    strength: 2,
    tags: ["easy", "cuban", "cola", "party"],
    created_at: "2025-01-01",
  },

  // TEQUILA COCKTAILS
  {
    id: "18",
    slug: "margarita",
    name: "Margarita",
    description: "The world's most popular cocktail. Tangy lime, smooth tequila, and a salted rim.",
    image: "/cocktails/margarita.jpg",
    ingredients: [
      { name: "Tequila", amount: "2", unit: "oz" },
      { name: "Lime Juice", amount: "1", unit: "oz" },
      { name: "Triple Sec", amount: "1", unit: "oz" },
    ],
    instructions: [
      "Rim glass with salt (optional)",
      "Shake all ingredients with ice",
      "Strain into a rocks glass with fresh ice",
      "Garnish with lime wheel",
    ],
    glass: "Rocks Glass",
    garnish: "Lime wheel, salt rim",
    baseSpirit: "tequila",
    category: "classic",
    difficulty: 1,
    strength: 4,
    tags: ["citrus", "mexican", "popular", "salt rim"],
    created_at: "2025-01-01",
  },
  {
    id: "19",
    slug: "tequila-sunrise",
    name: "Tequila Sunrise",
    description: "Beautiful layered cocktail that looks like a sunrise. Sweet, fruity, and Instagram-worthy.",
    image: "/cocktails/tequila-sunrise.jpg",
    ingredients: [
      { name: "Tequila", amount: "2", unit: "oz" },
      { name: "Orange Juice", amount: "4", unit: "oz" },
      { name: "Grenadine", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Fill a highball glass with ice",
      "Add tequila and orange juice, stir",
      "Slowly pour grenadine down the side",
      "Let it sink to create sunrise effect",
    ],
    glass: "Highball Glass",
    garnish: "Orange slice, cherry",
    baseSpirit: "tequila",
    category: "classic",
    difficulty: 1,
    strength: 3,
    tags: ["colorful", "sweet", "instagram", "easy"],
    created_at: "2025-01-01",
  },
  {
    id: "20",
    slug: "paloma",
    name: "Paloma",
    description: "Mexico's favorite tequila cocktail. Grapefruit, lime, and a hint of salt.",
    image: "/cocktails/paloma.jpg",
    ingredients: [
      { name: "Tequila", amount: "2", unit: "oz" },
      { name: "Grapefruit Soda", amount: "4", unit: "oz" },
      { name: "Lime Juice", amount: "0.5", unit: "oz" },
      { name: "Salt", amount: "pinch" },
    ],
    instructions: [
      "Rim glass with salt (optional)",
      "Fill with ice",
      "Add tequila and lime juice",
      "Top with grapefruit soda",
    ],
    glass: "Highball Glass",
    garnish: "Grapefruit wedge",
    baseSpirit: "tequila",
    category: "classic",
    difficulty: 1,
    strength: 3,
    tags: ["grapefruit", "mexican", "refreshing", "easy"],
    created_at: "2025-01-01",
  },
  {
    id: "21",
    slug: "tommy's-margarita",
    name: "Tommy's Margarita",
    description: "A modern classic using agave instead of triple sec. Pure tequila flavor shines.",
    image: "/cocktails/tommys-margarita.jpg",
    ingredients: [
      { name: "Tequila", amount: "2", unit: "oz" },
      { name: "Lime Juice", amount: "1", unit: "oz" },
      { name: "Agave Nectar", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Shake all ingredients with ice",
      "Strain into a rocks glass with ice",
      "Garnish with lime wheel",
    ],
    glass: "Rocks Glass",
    garnish: "Lime wheel",
    baseSpirit: "tequila",
    category: "classic",
    difficulty: 1,
    strength: 4,
    tags: ["modern classic", "agave", "citrus", "simple"],
    created_at: "2025-01-01",
  },

  // WHISKEY COCKTAILS
  {
    id: "22",
    slug: "old-fashioned",
    name: "Old Fashioned",
    description: "The original cocktail. Whiskey, sugar, bitters - timeless sophistication.",
    image: "/cocktails/old-fashioned.jpg",
    ingredients: [
      { name: "Bourbon", amount: "2", unit: "oz" },
      { name: "Sugar Cube", amount: "1" },
      { name: "Angostura Bitters", amount: "3", unit: "dashes" },
      { name: "Water", amount: "splash" },
    ],
    instructions: [
      "Muddle sugar with bitters and water",
      "Add bourbon and ice",
      "Stir until well chilled",
      "Garnish with orange peel",
    ],
    glass: "Rocks Glass",
    garnish: "Orange peel, cherry",
    baseSpirit: "whiskey",
    category: "classic",
    difficulty: 2,
    strength: 5,
    tags: ["classic", "stirred", "strong", "sophisticated"],
    created_at: "2025-01-01",
  },
  {
    id: "23",
    slug: "whiskey-sour",
    name: "Whiskey Sour",
    description: "A perfectly balanced whiskey cocktail. Sweet, sour, and silky smooth.",
    image: "/cocktails/whiskey-sour.jpg",
    ingredients: [
      { name: "Bourbon", amount: "2", unit: "oz" },
      { name: "Lemon Juice", amount: "0.75", unit: "oz" },
      { name: "Simple Syrup", amount: "0.75", unit: "oz" },
      { name: "Egg White", amount: "1", unit: "(optional)" },
    ],
    instructions: [
      "Dry shake all ingredients without ice",
      "Add ice and shake again",
      "Strain into a rocks glass",
      "Garnish with cherry and orange",
    ],
    glass: "Rocks Glass",
    garnish: "Cherry, orange slice",
    baseSpirit: "whiskey",
    category: "classic",
    difficulty: 2,
    strength: 4,
    tags: ["sour", "citrus", "egg white", "shaken"],
    created_at: "2025-01-01",
  },
  {
    id: "24",
    slug: "manhattan",
    name: "Manhattan",
    description: "The sophisticated older sibling of the Martini. Whiskey, vermouth, and bitters.",
    image: "/cocktails/manhattan.jpg",
    ingredients: [
      { name: "Rye Whiskey", amount: "2", unit: "oz" },
      { name: "Sweet Vermouth", amount: "1", unit: "oz" },
      { name: "Angostura Bitters", amount: "2", unit: "dashes" },
    ],
    instructions: [
      "Add all ingredients to a mixing glass with ice",
      "Stir until well chilled",
      "Strain into a chilled coupe glass",
      "Garnish with cherry",
    ],
    glass: "Coupe Glass",
    garnish: "Luxardo cherry",
    baseSpirit: "whiskey",
    category: "classic",
    difficulty: 2,
    strength: 5,
    tags: ["elegant", "stirred", "strong", "new york"],
    created_at: "2025-01-01",
  },
  {
    id: "25",
    slug: "mint-julep",
    name: "Mint Julep",
    description: "The Kentucky Derby classic. Bourbon and fresh mint over crushed ice.",
    image: "/cocktails/mint-julep.jpg",
    ingredients: [
      { name: "Bourbon", amount: "2.5", unit: "oz" },
      { name: "Fresh Mint", amount: "8-10", unit: "leaves" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Gently muddle mint with syrup in a julep cup",
      "Add bourbon",
      "Fill with crushed ice",
      "Stir and top with more crushed ice",
      "Garnish with mint bouquet",
    ],
    glass: "Julep Cup",
    garnish: "Mint bouquet",
    baseSpirit: "whiskey",
    category: "classic",
    difficulty: 2,
    strength: 4,
    tags: ["kentucky derby", "mint", "crushed ice", "southern"],
    created_at: "2025-01-01",
  },
  {
    id: "26",
    slug: "irish-coffee",
    name: "Irish Coffee",
    description: "Warm, cozy, and caffeinated. Irish whiskey, coffee, and cream.",
    image: "/cocktails/irish-coffee.jpg",
    ingredients: [
      { name: "Irish Whiskey", amount: "1.5", unit: "oz" },
      { name: "Hot Coffee", amount: "4", unit: "oz" },
      { name: "Brown Sugar", amount: "1", unit: "tsp" },
      { name: "Heavy Cream", amount: "1", unit: "oz" },
    ],
    instructions: [
      "Warm an Irish coffee glass",
      "Add whiskey, sugar, and hot coffee",
      "Stir to dissolve sugar",
      "Float lightly whipped cream on top",
    ],
    glass: "Irish Coffee Glass",
    garnish: "Whipped cream",
    baseSpirit: "whiskey",
    category: "classic",
    difficulty: 2,
    strength: 3,
    tags: ["warm", "coffee", "cream", "after dinner"],
    created_at: "2025-01-01",
  },
  {
    id: "27",
    slug: "boulevardier",
    name: "Boulevardier",
    description: "A Negroni's whiskey-based cousin. Rich, bitter, and complex.",
    image: "/cocktails/boulevardier.jpg",
    ingredients: [
      { name: "Bourbon", amount: "1.5", unit: "oz" },
      { name: "Sweet Vermouth", amount: "1", unit: "oz" },
      { name: "Campari", amount: "1", unit: "oz" },
    ],
    instructions: [
      "Add all ingredients to a mixing glass with ice",
      "Stir until well chilled",
      "Strain into a rocks glass with ice",
      "Garnish with orange peel",
    ],
    glass: "Rocks Glass",
    garnish: "Orange peel",
    baseSpirit: "whiskey",
    category: "classic",
    difficulty: 2,
    strength: 4,
    tags: ["bitter", "stirred", "aperitif", "negroni variant"],
    created_at: "2025-01-01",
  },

  // BRANDY COCKTAILS
  {
    id: "28",
    slug: "sidecar",
    name: "Sidecar",
    description: "A classic brandy sour with Cointreau. Elegant and citrus-forward.",
    image: "/cocktails/sidecar.jpg",
    ingredients: [
      { name: "Cognac", amount: "2", unit: "oz" },
      { name: "Cointreau", amount: "0.75", unit: "oz" },
      { name: "Lemon Juice", amount: "0.75", unit: "oz" },
    ],
    instructions: [
      "Rim glass with sugar (optional)",
      "Shake all ingredients with ice",
      "Strain into a chilled coupe glass",
    ],
    glass: "Coupe Glass",
    garnish: "Sugar rim, lemon twist",
    baseSpirit: "brandy",
    category: "classic",
    difficulty: 2,
    strength: 4,
    tags: ["citrus", "elegant", "french", "shaken"],
    created_at: "2025-01-01",
  },
  {
    id: "29",
    slug: "brandy-alexander",
    name: "Brandy Alexander",
    description: "A creamy, dessert-like cocktail. Perfect after-dinner indulgence.",
    image: "/cocktails/brandy-alexander.jpg",
    ingredients: [
      { name: "Cognac", amount: "1.5", unit: "oz" },
      { name: "Creme de Cacao", amount: "1", unit: "oz" },
      { name: "Heavy Cream", amount: "1", unit: "oz" },
    ],
    instructions: [
      "Shake all ingredients vigorously with ice",
      "Strain into a chilled coupe glass",
      "Garnish with grated nutmeg",
    ],
    glass: "Coupe Glass",
    garnish: "Grated nutmeg",
    baseSpirit: "brandy",
    category: "classic",
    difficulty: 1,
    strength: 3,
    tags: ["creamy", "dessert", "after dinner", "sweet"],
    created_at: "2025-01-01",
  },

  // SHOOTERS & PARTY DRINKS
  {
    id: "30",
    slug: "b-52",
    name: "B-52",
    description: "A layered shooter with coffee, Irish cream, and orange liqueur.",
    image: "/cocktails/b-52.jpg",
    ingredients: [
      { name: "Kahlua", amount: "0.5", unit: "oz" },
      { name: "Baileys", amount: "0.5", unit: "oz" },
      { name: "Grand Marnier", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Pour Kahlua into a shot glass",
      "Layer Baileys on top using a spoon",
      "Layer Grand Marnier on top",
      "Optionally set on fire before drinking",
    ],
    glass: "Shot Glass",
    baseSpirit: "various",
    category: "shooter",
    difficulty: 2,
    strength: 4,
    tags: ["layered", "coffee", "party", "flaming"],
    created_at: "2025-01-01",
  },
  {
    id: "31",
    slug: "kamikaze",
    name: "Kamikaze",
    description: "A classic vodka shooter. Tart, sweet, and packs a punch.",
    image: "/cocktails/kamikaze.jpg",
    ingredients: [
      { name: "Vodka", amount: "1", unit: "oz" },
      { name: "Triple Sec", amount: "1", unit: "oz" },
      { name: "Lime Juice", amount: "1", unit: "oz" },
    ],
    instructions: [
      "Shake all ingredients with ice",
      "Strain into a shot glass",
    ],
    glass: "Shot Glass",
    baseSpirit: "vodka",
    category: "shooter",
    difficulty: 1,
    strength: 4,
    tags: ["party", "citrus", "shot", "easy"],
    created_at: "2025-01-01",
  },
  {
    id: "32",
    slug: "lemon-drop-shot",
    name: "Lemon Drop Shot",
    description: "Sweet and sour vodka shot with a sugar-coated lemon chaser.",
    image: "/cocktails/lemon-drop-shot.jpg",
    ingredients: [
      { name: "Vodka", amount: "1.5", unit: "oz" },
      { name: "Lemon Juice", amount: "0.5", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Shake all ingredients with ice",
      "Strain into a shot glass",
      "Serve with a sugar-coated lemon wedge",
    ],
    glass: "Shot Glass",
    garnish: "Sugar-coated lemon",
    baseSpirit: "vodka",
    category: "shooter",
    difficulty: 1,
    strength: 4,
    tags: ["party", "sweet", "citrus", "popular"],
    created_at: "2025-01-01",
  },
  {
    id: "33",
    slug: "jello-shot",
    name: "Jello Shot",
    description: "The ultimate party shot. Vodka-infused jello in endless flavor combinations.",
    image: "/cocktails/jello-shot.jpg",
    ingredients: [
      { name: "Vodka", amount: "1", unit: "cup" },
      { name: "Water", amount: "1", unit: "cup (boiling)" },
      { name: "Jello Mix", amount: "1", unit: "packet (3oz)" },
    ],
    instructions: [
      "Dissolve Jello in boiling water",
      "Stir in cold vodka",
      "Pour into shot cups",
      "Refrigerate for 2-4 hours until set",
    ],
    glass: "Plastic Cup",
    baseSpirit: "vodka",
    category: "party",
    difficulty: 1,
    strength: 3,
    tags: ["party", "make ahead", "college", "fun"],
    created_at: "2025-01-01",
  },

  // PARTY PUNCHES
  {
    id: "34",
    slug: "jungle-juice",
    name: "Jungle Juice",
    description: "The legendary party punch. A fruity, boozy mix that serves a crowd.",
    image: "/cocktails/jungle-juice.jpg",
    ingredients: [
      { name: "Vodka", amount: "1", unit: "handle" },
      { name: "Rum", amount: "750", unit: "ml" },
      { name: "Fruit Punch", amount: "1", unit: "gallon" },
      { name: "Pineapple Juice", amount: "64", unit: "oz" },
      { name: "Sliced Fruit", amount: "assorted" },
    ],
    instructions: [
      "Combine all liquids in a large cooler or container",
      "Add sliced oranges, pineapples, and strawberries",
      "Stir well and refrigerate",
      "Serve over ice",
    ],
    glass: "Plastic Cup",
    garnish: "Fresh fruit",
    baseSpirit: "various",
    category: "party",
    difficulty: 1,
    strength: 4,
    tags: ["party", "punch", "serves many", "college"],
    created_at: "2025-01-01",
  },
  {
    id: "35",
    slug: "long-island-iced-tea",
    name: "Long Island Iced Tea",
    description: "Deceptively strong but tastes like iced tea. Five spirits in one glass.",
    image: "/cocktails/long-island-iced-tea.jpg",
    ingredients: [
      { name: "Vodka", amount: "0.5", unit: "oz" },
      { name: "Gin", amount: "0.5", unit: "oz" },
      { name: "Rum", amount: "0.5", unit: "oz" },
      { name: "Tequila", amount: "0.5", unit: "oz" },
      { name: "Triple Sec", amount: "0.5", unit: "oz" },
      { name: "Lemon Juice", amount: "0.75", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
      { name: "Cola", amount: "splash" },
    ],
    instructions: [
      "Add all spirits, lemon juice, and syrup to a shaker with ice",
      "Shake and strain into an ice-filled Collins glass",
      "Top with a splash of cola",
      "Garnish with lemon wedge",
    ],
    glass: "Collins Glass",
    garnish: "Lemon wedge",
    baseSpirit: "various",
    category: "party",
    difficulty: 2,
    strength: 5,
    tags: ["strong", "party", "deceptive", "classic"],
    created_at: "2025-01-01",
  },
  {
    id: "36",
    slug: "sex-on-the-beach",
    name: "Sex on the Beach",
    description: "Fruity, fun, and easy to drink. A beach vacation in a glass.",
    image: "/cocktails/sex-on-the-beach.jpg",
    ingredients: [
      { name: "Vodka", amount: "1.5", unit: "oz" },
      { name: "Peach Schnapps", amount: "0.75", unit: "oz" },
      { name: "Orange Juice", amount: "2", unit: "oz" },
      { name: "Cranberry Juice", amount: "2", unit: "oz" },
    ],
    instructions: [
      "Fill a highball glass with ice",
      "Add vodka and peach schnapps",
      "Add orange and cranberry juices",
      "Stir and garnish",
    ],
    glass: "Highball Glass",
    garnish: "Orange slice, cherry",
    baseSpirit: "vodka",
    category: "party",
    difficulty: 1,
    strength: 2,
    tags: ["fruity", "beach", "sweet", "easy"],
    created_at: "2025-01-01",
  },

  // MOCKTAILS
  {
    id: "37",
    slug: "virgin-mojito",
    name: "Virgin Mojito",
    description: "All the refreshing mint and lime without the alcohol. Perfect for designated drivers.",
    image: "/cocktails/virgin-mojito.jpg",
    ingredients: [
      { name: "Fresh Mint", amount: "8-10", unit: "leaves" },
      { name: "Lime Juice", amount: "1", unit: "oz" },
      { name: "Simple Syrup", amount: "0.75", unit: "oz" },
      { name: "Club Soda", amount: "4", unit: "oz" },
    ],
    instructions: [
      "Gently muddle mint with lime juice and syrup",
      "Add ice",
      "Top with club soda",
      "Stir gently and garnish",
    ],
    glass: "Highball Glass",
    garnish: "Mint sprig, lime wheel",
    baseSpirit: "none",
    category: "mocktail",
    difficulty: 1,
    strength: 1,
    tags: ["non-alcoholic", "refreshing", "mint", "summer"],
    created_at: "2025-01-01",
  },
  {
    id: "38",
    slug: "shirley-temple",
    name: "Shirley Temple",
    description: "The classic kiddie cocktail. Sweet, fizzy, and topped with cherries.",
    image: "/cocktails/shirley-temple.jpg",
    ingredients: [
      { name: "Ginger Ale", amount: "4", unit: "oz" },
      { name: "Lemon-Lime Soda", amount: "2", unit: "oz" },
      { name: "Grenadine", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Fill a glass with ice",
      "Add ginger ale and lemon-lime soda",
      "Add grenadine",
      "Garnish with cherries",
    ],
    glass: "Highball Glass",
    garnish: "Maraschino cherries",
    baseSpirit: "none",
    category: "mocktail",
    difficulty: 1,
    strength: 1,
    tags: ["non-alcoholic", "sweet", "classic", "kid-friendly"],
    created_at: "2025-01-01",
  },
  {
    id: "39",
    slug: "arnold-palmer",
    name: "Arnold Palmer",
    description: "Half iced tea, half lemonade. Named after the legendary golfer.",
    image: "/cocktails/arnold-palmer.jpg",
    ingredients: [
      { name: "Iced Tea", amount: "4", unit: "oz" },
      { name: "Lemonade", amount: "4", unit: "oz" },
    ],
    instructions: [
      "Fill a glass with ice",
      "Add equal parts iced tea and lemonade",
      "Stir and garnish with lemon",
    ],
    glass: "Highball Glass",
    garnish: "Lemon wedge",
    baseSpirit: "none",
    category: "mocktail",
    difficulty: 1,
    strength: 1,
    tags: ["non-alcoholic", "tea", "refreshing", "golf"],
    created_at: "2025-01-01",
  },

  // BEER COCKTAILS
  {
    id: "40",
    slug: "michelada",
    name: "Michelada",
    description: "A spicy Mexican beer cocktail. Like a Bloody Mary with beer.",
    image: "/cocktails/michelada.jpg",
    ingredients: [
      { name: "Mexican Lager", amount: "12", unit: "oz" },
      { name: "Lime Juice", amount: "1", unit: "oz" },
      { name: "Hot Sauce", amount: "3", unit: "dashes" },
      { name: "Worcestershire", amount: "2", unit: "dashes" },
      { name: "Tajin", amount: "for rim" },
    ],
    instructions: [
      "Rim a glass with Tajin",
      "Add lime juice, hot sauce, and Worcestershire",
      "Fill with ice",
      "Top with beer",
      "Stir gently",
    ],
    glass: "Pint Glass",
    garnish: "Lime wedge, Tajin rim",
    baseSpirit: "none",
    category: "beer-cocktail",
    difficulty: 1,
    strength: 2,
    tags: ["spicy", "mexican", "beer", "savory"],
    created_at: "2025-01-01",
  },
  {
    id: "41",
    slug: "black-velvet",
    name: "Black Velvet",
    description: "A luxurious mix of stout and champagne. Surprisingly delicious.",
    image: "/cocktails/black-velvet.jpg",
    ingredients: [
      { name: "Stout Beer", amount: "4", unit: "oz" },
      { name: "Champagne", amount: "4", unit: "oz" },
    ],
    instructions: [
      "Pour champagne into a flute",
      "Slowly layer stout on top",
    ],
    glass: "Champagne Flute",
    baseSpirit: "none",
    category: "beer-cocktail",
    difficulty: 2,
    strength: 2,
    tags: ["elegant", "champagne", "stout", "layered"],
    created_at: "2025-01-01",
  },
  {
    id: "42",
    slug: "shandy",
    name: "Shandy",
    description: "A refreshing beer and lemonade mix. Perfect for hot summer days.",
    image: "/cocktails/shandy.jpg",
    ingredients: [
      { name: "Lager Beer", amount: "6", unit: "oz" },
      { name: "Lemonade", amount: "6", unit: "oz" },
    ],
    instructions: [
      "Fill a pint glass halfway with lemonade",
      "Top with beer",
      "Stir gently",
    ],
    glass: "Pint Glass",
    garnish: "Lemon wedge",
    baseSpirit: "none",
    category: "beer-cocktail",
    difficulty: 1,
    strength: 1,
    tags: ["refreshing", "summer", "easy", "light"],
    created_at: "2025-01-01",
  },

  // MORE CLASSICS
  {
    id: "43",
    slug: "amaretto-sour",
    name: "Amaretto Sour",
    description: "Sweet almond liqueur balanced with citrus. Smooth and approachable.",
    image: "/cocktails/amaretto-sour.jpg",
    ingredients: [
      { name: "Amaretto", amount: "1.5", unit: "oz" },
      { name: "Bourbon", amount: "0.75", unit: "oz" },
      { name: "Lemon Juice", amount: "1", unit: "oz" },
      { name: "Simple Syrup", amount: "0.25", unit: "oz" },
      { name: "Egg White", amount: "1", unit: "(optional)" },
    ],
    instructions: [
      "Dry shake all ingredients without ice",
      "Add ice and shake again",
      "Strain into a rocks glass with ice",
      "Garnish with cherry",
    ],
    glass: "Rocks Glass",
    garnish: "Maraschino cherry",
    baseSpirit: "various",
    category: "classic",
    difficulty: 2,
    strength: 3,
    tags: ["almond", "sweet", "sour", "approachable"],
    created_at: "2025-01-01",
  },
  {
    id: "44",
    slug: "aperol-spritz",
    name: "Aperol Spritz",
    description: "Italy's favorite aperitivo. Light, bitter-sweet, and bubbly.",
    image: "/cocktails/aperol-spritz.jpg",
    ingredients: [
      { name: "Aperol", amount: "2", unit: "oz" },
      { name: "Prosecco", amount: "3", unit: "oz" },
      { name: "Club Soda", amount: "1", unit: "oz" },
    ],
    instructions: [
      "Fill a wine glass with ice",
      "Add Aperol and Prosecco",
      "Top with club soda",
      "Garnish with orange slice",
    ],
    glass: "Wine Glass",
    garnish: "Orange slice",
    baseSpirit: "various",
    category: "classic",
    difficulty: 1,
    strength: 2,
    tags: ["italian", "aperitivo", "bubbly", "orange"],
    created_at: "2025-01-01",
  },
  {
    id: "45",
    slug: "white-russian",
    name: "White Russian",
    description: "The Dude's drink of choice. Vodka, coffee liqueur, and cream.",
    image: "/cocktails/white-russian.jpg",
    ingredients: [
      { name: "Vodka", amount: "2", unit: "oz" },
      { name: "Coffee Liqueur", amount: "1", unit: "oz" },
      { name: "Heavy Cream", amount: "1", unit: "oz" },
    ],
    instructions: [
      "Fill a rocks glass with ice",
      "Add vodka and coffee liqueur",
      "Float cream on top",
      "Stir if desired",
    ],
    glass: "Rocks Glass",
    baseSpirit: "vodka",
    category: "classic",
    difficulty: 1,
    strength: 3,
    tags: ["creamy", "coffee", "the dude", "easy"],
    created_at: "2025-01-01",
  },
  {
    id: "46",
    slug: "hurricane",
    name: "Hurricane",
    description: "A New Orleans classic. Fruity, potent, and perfect for Mardi Gras.",
    image: "/cocktails/hurricane.jpg",
    ingredients: [
      { name: "Light Rum", amount: "2", unit: "oz" },
      { name: "Dark Rum", amount: "2", unit: "oz" },
      { name: "Passion Fruit Juice", amount: "2", unit: "oz" },
      { name: "Orange Juice", amount: "1", unit: "oz" },
      { name: "Lime Juice", amount: "0.5", unit: "oz" },
      { name: "Simple Syrup", amount: "1", unit: "oz" },
      { name: "Grenadine", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Shake all ingredients with ice",
      "Strain into a hurricane glass with ice",
      "Garnish with orange and cherry",
    ],
    glass: "Hurricane Glass",
    garnish: "Orange slice, cherry",
    baseSpirit: "rum",
    category: "tropical",
    difficulty: 2,
    strength: 4,
    tags: ["new orleans", "tropical", "fruity", "strong"],
    created_at: "2025-01-01",
  },
  {
    id: "47",
    slug: "pisco-sour",
    name: "Pisco Sour",
    description: "Peru's national cocktail. Tangy, frothy, and utterly unique.",
    image: "/cocktails/pisco-sour.jpg",
    ingredients: [
      { name: "Pisco", amount: "2", unit: "oz" },
      { name: "Lime Juice", amount: "1", unit: "oz" },
      { name: "Simple Syrup", amount: "0.75", unit: "oz" },
      { name: "Egg White", amount: "1" },
      { name: "Angostura Bitters", amount: "3", unit: "drops" },
    ],
    instructions: [
      "Dry shake all ingredients except bitters",
      "Add ice and shake again",
      "Strain into a coupe glass",
      "Add bitters drops on foam",
    ],
    glass: "Coupe Glass",
    garnish: "Angostura bitters design",
    baseSpirit: "brandy",
    category: "classic",
    difficulty: 2,
    strength: 4,
    tags: ["peruvian", "egg white", "sour", "frothy"],
    created_at: "2025-01-01",
  },
  {
    id: "48",
    slug: "caipirinha",
    name: "Caipirinha",
    description: "Brazil's national cocktail. Muddled lime, sugar, and cachaca.",
    image: "/cocktails/caipirinha.jpg",
    ingredients: [
      { name: "Cachaca", amount: "2", unit: "oz" },
      { name: "Lime", amount: "1", unit: "whole, quartered" },
      { name: "Sugar", amount: "2", unit: "tsp" },
    ],
    instructions: [
      "Muddle lime quarters with sugar in a rocks glass",
      "Add cachaca",
      "Fill with ice",
      "Stir well",
    ],
    glass: "Rocks Glass",
    garnish: "Lime wheel",
    baseSpirit: "rum",
    category: "classic",
    difficulty: 1,
    strength: 4,
    tags: ["brazilian", "lime", "muddled", "refreshing"],
    created_at: "2025-01-01",
  },
  {
    id: "49",
    slug: "singapore-sling",
    name: "Singapore Sling",
    description: "A complex gin-based classic from Singapore's Raffles Hotel.",
    image: "/cocktails/singapore-sling.jpg",
    ingredients: [
      { name: "Gin", amount: "1.5", unit: "oz" },
      { name: "Cherry Heering", amount: "0.5", unit: "oz" },
      { name: "Cointreau", amount: "0.25", unit: "oz" },
      { name: "Benedictine", amount: "0.25", unit: "oz" },
      { name: "Pineapple Juice", amount: "4", unit: "oz" },
      { name: "Lime Juice", amount: "0.5", unit: "oz" },
      { name: "Grenadine", amount: "0.25", unit: "oz" },
      { name: "Angostura Bitters", amount: "1", unit: "dash" },
    ],
    instructions: [
      "Shake all ingredients with ice",
      "Strain into a sling glass with ice",
      "Garnish with pineapple and cherry",
    ],
    glass: "Sling Glass",
    garnish: "Pineapple, cherry",
    baseSpirit: "gin",
    category: "classic",
    difficulty: 3,
    strength: 3,
    tags: ["complex", "tropical", "singapore", "tiki"],
    created_at: "2025-01-01",
  },
  {
    id: "50",
    slug: "sazerac",
    name: "Sazerac",
    description: "New Orleans' official cocktail. Rye, absinthe rinse, and Peychaud's bitters.",
    image: "/cocktails/sazerac.jpg",
    ingredients: [
      { name: "Rye Whiskey", amount: "2", unit: "oz" },
      { name: "Sugar Cube", amount: "1" },
      { name: "Peychaud's Bitters", amount: "3", unit: "dashes" },
      { name: "Absinthe", amount: "rinse" },
    ],
    instructions: [
      "Rinse a chilled rocks glass with absinthe, discard excess",
      "Muddle sugar with bitters in a mixing glass",
      "Add rye and ice, stir until well chilled",
      "Strain into the prepared glass (no ice)",
      "Garnish with lemon peel",
    ],
    glass: "Rocks Glass",
    garnish: "Lemon peel",
    baseSpirit: "whiskey",
    category: "classic",
    difficulty: 3,
    strength: 5,
    tags: ["new orleans", "absinthe", "classic", "strong"],
    created_at: "2025-01-01",
  },
];

// Helper functions
export const getCocktailBySlug = (slug: string): Cocktail | undefined => {
  return cocktails.find((c) => c.slug === slug);
};

export const getCocktailsBySpirit = (spirit: Cocktail["baseSpirit"]): Cocktail[] => {
  return cocktails.filter((c) => c.baseSpirit === spirit);
};

export const getCocktailsByCategory = (category: Cocktail["category"]): Cocktail[] => {
  return cocktails.filter((c) => c.category === category);
};

export const searchCocktails = (query: string): Cocktail[] => {
  const q = query.toLowerCase();
  return cocktails.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.description.toLowerCase().includes(q) ||
      c.tags.some((t) => t.toLowerCase().includes(q)) ||
      c.ingredients.some((i) => i.name.toLowerCase().includes(q))
  );
};
