import { Cocktail } from "@/types";

export type DrinkCategorySlug = "cocktails" | "shots" | "punches" | "mocktails";

export type DrinkRecipe = Cocktail & {
  categorySlug: DrinkCategorySlug;
  servingSize: string;
  proTips: string[];
};

const defaultDrinkTimestamp = "2026-03-20";

export const drinks: DrinkRecipe[] = [
  // Cocktails (20)
  {
    id: "drink-1",
    slug: "margarita",
    name: "Margarita",
    description: "A bright, citrus-forward tequila cocktail with a salted rim.",
    ingredients: [
      { name: "Tequila", amount: "2", unit: "oz" },
      { name: "Triple Sec", amount: "1", unit: "oz" },
      { name: "Fresh Lime Juice", amount: "1", unit: "oz" },
      { name: "Agave Syrup", amount: "0.25", unit: "oz" },
      { name: "Salt", amount: "pinch" },
    ],
    instructions: [
      "Rim a rocks glass with salt and fill with ice",
      "Shake tequila, triple sec, lime juice, and agave with ice",
      "Strain into the prepared glass",
      "Garnish with a lime wheel",
    ],
    glass: "Rocks Glass",
    garnish: "Lime wheel",
    baseSpirit: "tequila",
    category: "classic",
    difficulty: 1,
    strength: 4,
    tags: ["citrus", "tequila", "classic", "salted rim"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Use fresh lime juice for the best balance", "Chill the glass before serving"],
  },
  {
    id: "drink-2",
    slug: "frozen-margarita",
    name: "Frozen Margarita",
    description: "A slushy, icy version of the classic margarita.",
    ingredients: [
      { name: "Tequila", amount: "2", unit: "oz" },
      { name: "Triple Sec", amount: "1", unit: "oz" },
      { name: "Lime Juice", amount: "1", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
      { name: "Ice", amount: "1.5", unit: "cups" },
    ],
    instructions: [
      "Add all ingredients to a blender",
      "Blend until smooth and slushy",
      "Pour into a chilled margarita glass",
      "Garnish with a lime wedge",
    ],
    glass: "Margarita Glass",
    garnish: "Lime wedge",
    baseSpirit: "tequila",
    category: "tropical",
    difficulty: 1,
    strength: 4,
    tags: ["frozen", "blended", "tequila"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Use crushed ice for a smoother blend", "Chill the blender jar beforehand"],
  },
  {
    id: "drink-3",
    slug: "spicy-margarita",
    name: "Spicy Margarita",
    description: "A margarita with a jalapeno kick and bright lime finish.",
    ingredients: [
      { name: "Tequila", amount: "2", unit: "oz" },
      { name: "Triple Sec", amount: "1", unit: "oz" },
      { name: "Lime Juice", amount: "1", unit: "oz" },
      { name: "Agave Syrup", amount: "0.25", unit: "oz" },
      { name: "Jalapeno Slices", amount: "2" },
    ],
    instructions: [
      "Muddle jalapeno slices in a shaker",
      "Add tequila, triple sec, lime, and agave with ice",
      "Shake hard and strain into a rocks glass over ice",
      "Garnish with a jalapeno slice",
    ],
    glass: "Rocks Glass",
    garnish: "Jalapeno slice",
    baseSpirit: "tequila",
    category: "classic",
    difficulty: 2,
    strength: 4,
    tags: ["spicy", "tequila", "lime"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Remove seeds for less heat", "Shake extra to mellow the spice"],
  },
  {
    id: "drink-4",
    slug: "mango-margarita",
    name: "Mango Margarita",
    description: "Tropical mango and lime with a tequila backbone.",
    ingredients: [
      { name: "Tequila", amount: "2", unit: "oz" },
      { name: "Triple Sec", amount: "1", unit: "oz" },
      { name: "Mango Puree", amount: "1", unit: "oz" },
      { name: "Lime Juice", amount: "0.75", unit: "oz" },
    ],
    instructions: [
      "Add all ingredients to a shaker with ice",
      "Shake until chilled",
      "Strain into an ice-filled glass",
      "Garnish with a mango slice",
    ],
    glass: "Rocks Glass",
    garnish: "Mango slice",
    baseSpirit: "tequila",
    category: "tropical",
    difficulty: 1,
    strength: 4,
    tags: ["mango", "tropical", "tequila"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Use ripe mango or quality puree", "Add Tajin to the rim for extra flavor"],
  },
  {
    id: "drink-5",
    slug: "mojito",
    name: "Mojito",
    description: "A crisp rum highball with mint, lime, and bubbles.",
    ingredients: [
      { name: "White Rum", amount: "2", unit: "oz" },
      { name: "Lime Juice", amount: "0.75", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
      { name: "Mint Leaves", amount: "8", unit: "leaves" },
      { name: "Club Soda", amount: "3", unit: "oz" },
    ],
    instructions: [
      "Muddle mint with simple syrup in a highball glass",
      "Add rum and lime juice over ice",
      "Top with club soda and stir gently",
      "Garnish with mint sprig",
    ],
    glass: "Highball Glass",
    garnish: "Mint sprig",
    baseSpirit: "rum",
    category: "classic",
    difficulty: 2,
    strength: 3,
    tags: ["mint", "refreshing", "rum"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Lightly slap mint before garnishing", "Avoid over-muddling to prevent bitterness"],
  },
  {
    id: "drink-6",
    slug: "moscow-mule-drink",
    name: "Moscow Mule",
    description: "Ginger beer, lime, and vodka served ice-cold.",
    ingredients: [
      { name: "Vodka", amount: "2", unit: "oz" },
      { name: "Ginger Beer", amount: "4", unit: "oz" },
      { name: "Lime Juice", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Fill a copper mug with ice",
      "Add vodka and lime juice",
      "Top with ginger beer and stir",
      "Garnish with a lime wheel",
    ],
    glass: "Copper Mug",
    garnish: "Lime wheel",
    baseSpirit: "vodka",
    category: "classic",
    difficulty: 1,
    strength: 3,
    tags: ["ginger", "vodka", "easy"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Use spicy ginger beer for more bite", "Serve with plenty of ice"],
  },
  {
    id: "drink-7",
    slug: "espresso-martini",
    name: "Espresso Martini",
    description: "A rich, caffeinated cocktail with vodka and espresso.",
    ingredients: [
      { name: "Vodka", amount: "2", unit: "oz" },
      { name: "Espresso", amount: "1", unit: "oz" },
      { name: "Coffee Liqueur", amount: "0.5", unit: "oz" },
      { name: "Simple Syrup", amount: "0.25", unit: "oz" },
    ],
    instructions: [
      "Shake all ingredients with ice until frothy",
      "Strain into a chilled martini glass",
      "Garnish with three coffee beans",
    ],
    glass: "Martini Glass",
    garnish: "Coffee beans",
    baseSpirit: "vodka",
    category: "classic",
    difficulty: 2,
    strength: 4,
    tags: ["coffee", "vodka", "after-dinner"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Use fresh espresso for better crema", "Shake hard for a foamy top"],
  },
  {
    id: "drink-8",
    slug: "long-island-iced-tea",
    name: "Long Island Iced Tea",
    description: "A strong mix of spirits balanced with citrus and cola.",
    ingredients: [
      { name: "Vodka", amount: "0.5", unit: "oz" },
      { name: "Gin", amount: "0.5", unit: "oz" },
      { name: "White Rum", amount: "0.5", unit: "oz" },
      { name: "Tequila", amount: "0.5", unit: "oz" },
      { name: "Triple Sec", amount: "0.5", unit: "oz" },
      { name: "Lemon Juice", amount: "0.75", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
      { name: "Cola", amount: "2", unit: "oz" },
    ],
    instructions: [
      "Shake all spirits with lemon juice and simple syrup",
      "Strain into a highball glass with ice",
      "Top with cola and gently stir",
      "Garnish with a lemon wedge",
    ],
    glass: "Highball Glass",
    garnish: "Lemon wedge",
    baseSpirit: "various",
    category: "party",
    difficulty: 2,
    strength: 5,
    tags: ["strong", "party", "cola"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Measure carefully to keep balance", "Use plenty of ice to mellow the strength"],
  },
  {
    id: "drink-9",
    slug: "whiskey-sour-drink",
    name: "Whiskey Sour",
    description: "A balanced whiskey cocktail with lemon and sweetness.",
    ingredients: [
      { name: "Bourbon", amount: "2", unit: "oz" },
      { name: "Lemon Juice", amount: "0.75", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
      { name: "Egg White", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Dry shake all ingredients without ice",
      "Add ice and shake again",
      "Strain into a rocks glass over ice",
      "Garnish with bitters and lemon peel",
    ],
    glass: "Rocks Glass",
    garnish: "Lemon peel",
    baseSpirit: "whiskey",
    category: "classic",
    difficulty: 2,
    strength: 4,
    tags: ["whiskey", "sour", "classic"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Skip egg white for a lighter version", "Use fresh lemon juice"],
  },
  {
    id: "drink-10",
    slug: "old-fashioned-drink",
    name: "Old Fashioned",
    description: "A spirit-forward classic with sugar, bitters, and citrus oils.",
    ingredients: [
      { name: "Bourbon", amount: "2", unit: "oz" },
      { name: "Simple Syrup", amount: "0.25", unit: "oz" },
      { name: "Angostura Bitters", amount: "2", unit: "dashes" },
      { name: "Orange Peel", amount: "1" },
    ],
    instructions: [
      "Add syrup and bitters to a rocks glass",
      "Add bourbon and stir with ice",
      "Express orange peel oils over the glass",
      "Garnish with the peel",
    ],
    glass: "Rocks Glass",
    garnish: "Orange peel",
    baseSpirit: "whiskey",
    category: "classic",
    difficulty: 1,
    strength: 5,
    tags: ["whiskey", "spirit-forward", "classic"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Use a large ice cube for slow dilution", "Try a sugar cube for tradition"],
  },
  {
    id: "drink-11",
    slug: "cosmopolitan-drink",
    name: "Cosmopolitan",
    description: "A tart, citrusy vodka cocktail with cranberry and orange notes.",
    ingredients: [
      { name: "Vodka", amount: "1.5", unit: "oz" },
      { name: "Triple Sec", amount: "0.75", unit: "oz" },
      { name: "Lime Juice", amount: "0.5", unit: "oz" },
      { name: "Cranberry Juice", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Shake all ingredients with ice",
      "Strain into a chilled martini glass",
      "Garnish with an orange twist",
    ],
    glass: "Martini Glass",
    garnish: "Orange twist",
    baseSpirit: "vodka",
    category: "classic",
    difficulty: 2,
    strength: 4,
    tags: ["vodka", "citrus", "cranberry"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Chill the glass for a crisp finish", "Use fresh lime juice"],
  },
  {
    id: "drink-12",
    slug: "pina-colada",
    name: "Pina Colada",
    description: "Creamy pineapple and coconut with rum for a beachy classic.",
    ingredients: [
      { name: "White Rum", amount: "2", unit: "oz" },
      { name: "Coconut Cream", amount: "1.5", unit: "oz" },
      { name: "Pineapple Juice", amount: "3", unit: "oz" },
      { name: "Ice", amount: "1", unit: "cup" },
    ],
    instructions: [
      "Blend all ingredients until smooth",
      "Pour into a hurricane glass",
      "Garnish with pineapple and cherry",
    ],
    glass: "Hurricane Glass",
    garnish: "Pineapple wedge",
    baseSpirit: "rum",
    category: "tropical",
    difficulty: 1,
    strength: 3,
    tags: ["tropical", "coconut", "rum"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Use crushed ice for a smoother blend", "Add a dash of nutmeg for depth"],
  },
  {
    id: "drink-13",
    slug: "tequila-sunrise-drink",
    name: "Tequila Sunrise",
    description: "A layered tequila drink with orange juice and grenadine.",
    ingredients: [
      { name: "Tequila", amount: "2", unit: "oz" },
      { name: "Orange Juice", amount: "4", unit: "oz" },
      { name: "Grenadine", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Fill a highball glass with ice",
      "Add tequila and orange juice",
      "Slowly pour grenadine to create a sunrise effect",
      "Garnish with orange slice",
    ],
    glass: "Highball Glass",
    garnish: "Orange slice",
    baseSpirit: "tequila",
    category: "classic",
    difficulty: 1,
    strength: 3,
    tags: ["tequila", "orange", "easy"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Pour grenadine slowly for clean layers", "Use fresh orange juice"],
  },
  {
    id: "drink-14",
    slug: "negroni",
    name: "Negroni",
    description: "A bold, bitter-sweet cocktail with gin, Campari, and vermouth.",
    ingredients: [
      { name: "Gin", amount: "1", unit: "oz" },
      { name: "Campari", amount: "1", unit: "oz" },
      { name: "Sweet Vermouth", amount: "1", unit: "oz" },
    ],
    instructions: [
      "Stir ingredients with ice",
      "Strain into a rocks glass with a large ice cube",
      "Garnish with an orange peel",
    ],
    glass: "Rocks Glass",
    garnish: "Orange peel",
    baseSpirit: "gin",
    category: "classic",
    difficulty: 1,
    strength: 4,
    tags: ["bitter", "gin", "aperitif"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Use a large cube to slow dilution", "Swap gin for mezcal for a smoky twist"],
  },
  {
    id: "drink-15",
    slug: "daiquiri",
    name: "Daiquiri",
    description: "A clean, citrusy rum sour served up.",
    ingredients: [
      { name: "White Rum", amount: "2", unit: "oz" },
      { name: "Lime Juice", amount: "0.75", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Shake all ingredients with ice",
      "Strain into a chilled coupe",
      "Garnish with a lime twist",
    ],
    glass: "Coupe Glass",
    garnish: "Lime twist",
    baseSpirit: "rum",
    category: "classic",
    difficulty: 1,
    strength: 4,
    tags: ["rum", "sour", "classic"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Balance sweetness to taste", "Chill the coupe for a crisp serve"],
  },
  {
    id: "drink-16",
    slug: "french-75",
    name: "French 75",
    description: "Gin, lemon, and bubbles for a sparkling classic.",
    ingredients: [
      { name: "Gin", amount: "1.5", unit: "oz" },
      { name: "Lemon Juice", amount: "0.5", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
      { name: "Champagne", amount: "3", unit: "oz" },
    ],
    instructions: [
      "Shake gin, lemon, and syrup with ice",
      "Strain into a flute",
      "Top with champagne and garnish with lemon twist",
    ],
    glass: "Champagne Flute",
    garnish: "Lemon twist",
    baseSpirit: "gin",
    category: "classic",
    difficulty: 2,
    strength: 3,
    tags: ["sparkling", "gin", "celebration"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Use dry sparkling wine for balance", "Chill all ingredients"],
  },
  {
    id: "drink-17",
    slug: "paloma",
    name: "Paloma",
    description: "A refreshing tequila and grapefruit highball.",
    ingredients: [
      { name: "Tequila", amount: "2", unit: "oz" },
      { name: "Grapefruit Soda", amount: "4", unit: "oz" },
      { name: "Lime Juice", amount: "0.5", unit: "oz" },
      { name: "Salt", amount: "pinch" },
    ],
    instructions: [
      "Rim a glass with salt and fill with ice",
      "Add tequila and lime juice",
      "Top with grapefruit soda and stir",
      "Garnish with a grapefruit wedge",
    ],
    glass: "Highball Glass",
    garnish: "Grapefruit wedge",
    baseSpirit: "tequila",
    category: "classic",
    difficulty: 1,
    strength: 3,
    tags: ["tequila", "grapefruit", "refreshing"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Use fresh grapefruit juice plus soda", "Salted rim boosts citrus"],
  },
  {
    id: "drink-18",
    slug: "aperol-spritz",
    name: "Aperol Spritz",
    description: "A light, bittersweet spritz with Aperol and prosecco.",
    ingredients: [
      { name: "Aperol", amount: "2", unit: "oz" },
      { name: "Prosecco", amount: "3", unit: "oz" },
      { name: "Club Soda", amount: "1", unit: "oz" },
    ],
    instructions: [
      "Fill a wine glass with ice",
      "Add Aperol and prosecco",
      "Top with club soda and stir",
      "Garnish with an orange slice",
    ],
    glass: "Wine Glass",
    garnish: "Orange slice",
    baseSpirit: "various",
    category: "classic",
    difficulty: 1,
    strength: 2,
    tags: ["spritz", "aperitif", "low ABV"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Use plenty of ice for proper dilution", "Keep proportions 3-2-1"],
  },
  {
    id: "drink-19",
    slug: "mai-tai",
    name: "Mai Tai",
    description: "A tropical rum cocktail with almond and citrus notes.",
    ingredients: [
      { name: "Aged Rum", amount: "2", unit: "oz" },
      { name: "Orange Curacao", amount: "0.5", unit: "oz" },
      { name: "Orgeat", amount: "0.5", unit: "oz" },
      { name: "Lime Juice", amount: "0.75", unit: "oz" },
    ],
    instructions: [
      "Shake all ingredients with ice",
      "Pour into a rocks glass over crushed ice",
      "Garnish with mint and lime",
    ],
    glass: "Rocks Glass",
    garnish: "Mint sprig",
    baseSpirit: "rum",
    category: "tropical",
    difficulty: 2,
    strength: 4,
    tags: ["tiki", "rum", "tropical"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Use quality orgeat for best flavor", "Crushed ice is essential"],
  },
  {
    id: "drink-20",
    slug: "tom-collins",
    name: "Tom Collins",
    description: "A tall gin sour topped with soda water.",
    ingredients: [
      { name: "Gin", amount: "2", unit: "oz" },
      { name: "Lemon Juice", amount: "0.75", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
      { name: "Club Soda", amount: "3", unit: "oz" },
    ],
    instructions: [
      "Shake gin, lemon, and syrup with ice",
      "Strain into a highball glass over ice",
      "Top with soda and stir",
      "Garnish with a lemon wheel",
    ],
    glass: "Highball Glass",
    garnish: "Lemon wheel",
    baseSpirit: "gin",
    category: "classic",
    difficulty: 1,
    strength: 3,
    tags: ["gin", "citrus", "classic"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "cocktails",
    servingSize: "1 cocktail",
    proTips: ["Chill the glass to keep it crisp", "Adjust sweetness to taste"],
  },

  // Shots (15)
  {
    id: "drink-21",
    slug: "lemon-drop-shot",
    name: "Lemon Drop Shot",
    description: "A sweet-tart vodka shot with a sugared rim.",
    ingredients: [
      { name: "Vodka", amount: "1.5", unit: "oz" },
      { name: "Lemon Juice", amount: "0.5", unit: "oz" },
      { name: "Simple Syrup", amount: "0.25", unit: "oz" },
      { name: "Sugar", amount: "pinch" },
    ],
    instructions: [
      "Rim a shot glass with sugar",
      "Shake vodka, lemon juice, and syrup with ice",
      "Strain into the shot glass",
    ],
    glass: "Shot Glass",
    garnish: "Lemon twist",
    baseSpirit: "vodka",
    category: "shooter",
    difficulty: 1,
    strength: 4,
    tags: ["vodka", "citrus", "sweet"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "shots",
    servingSize: "1 shot",
    proTips: ["Use superfine sugar for a smooth rim", "Shake hard to chill"],
  },
  {
    id: "drink-22",
    slug: "kamikaze-shot",
    name: "Kamikaze",
    description: "A clean vodka shot with lime and triple sec.",
    ingredients: [
      { name: "Vodka", amount: "1", unit: "oz" },
      { name: "Triple Sec", amount: "1", unit: "oz" },
      { name: "Lime Juice", amount: "1", unit: "oz" },
    ],
    instructions: [
      "Shake all ingredients with ice",
      "Strain into a chilled shot glass",
    ],
    glass: "Shot Glass",
    garnish: "Lime wedge",
    baseSpirit: "vodka",
    category: "shooter",
    difficulty: 1,
    strength: 4,
    tags: ["vodka", "lime", "classic shot"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "shots",
    servingSize: "1 shot",
    proTips: ["Chill the shot glass first", "Use fresh lime juice"],
  },
  {
    id: "drink-23",
    slug: "b-52-shot",
    name: "B-52",
    description: "A layered coffee-and-cream shot with triple sec on top.",
    ingredients: [
      { name: "Coffee Liqueur", amount: "0.5", unit: "oz" },
      { name: "Irish Cream", amount: "0.5", unit: "oz" },
      { name: "Triple Sec", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Layer coffee liqueur, Irish cream, then triple sec",
      "Serve immediately",
    ],
    glass: "Shot Glass",
    garnish: "None",
    baseSpirit: "various",
    category: "shooter",
    difficulty: 2,
    strength: 4,
    tags: ["layered", "sweet", "dessert"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "shots",
    servingSize: "1 shot",
    proTips: ["Use the back of a spoon for clean layers", "Chill ingredients"],
  },
  {
    id: "drink-24",
    slug: "buttery-nipple-shot",
    name: "Buttery Nipple",
    description: "A sweet, creamy layered shot with butterscotch flavor.",
    ingredients: [
      { name: "Butterscotch Schnapps", amount: "1", unit: "oz" },
      { name: "Irish Cream", amount: "1", unit: "oz" },
    ],
    instructions: [
      "Pour butterscotch schnapps into a shot glass",
      "Float Irish cream on top",
    ],
    glass: "Shot Glass",
    garnish: "None",
    baseSpirit: "various",
    category: "shooter",
    difficulty: 1,
    strength: 3,
    tags: ["sweet", "creamy", "layered"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "shots",
    servingSize: "1 shot",
    proTips: ["Pour slowly to keep layers clean", "Serve chilled"],
  },
  {
    id: "drink-25",
    slug: "jager-bomb",
    name: "Jager Bomb",
    description: "An energy drink shot with Jagermeister.",
    ingredients: [
      { name: "Jagermeister", amount: "1.5", unit: "oz" },
      { name: "Energy Drink", amount: "4", unit: "oz" },
    ],
    instructions: [
      "Fill a glass with energy drink",
      "Drop a shot of Jagermeister into the glass",
      "Drink immediately",
    ],
    glass: "Shot Glass",
    garnish: "None",
    baseSpirit: "various",
    category: "shooter",
    difficulty: 1,
    strength: 4,
    tags: ["energy", "party", "bomb"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "shots",
    servingSize: "1 bomb",
    proTips: ["Use chilled energy drink", "Pour carefully to avoid spills"],
  },
  {
    id: "drink-26",
    slug: "green-tea-shot",
    name: "Green Tea Shot",
    description: "A smooth, sweet shot that tastes like green tea.",
    ingredients: [
      { name: "Irish Whiskey", amount: "1", unit: "oz" },
      { name: "Peach Schnapps", amount: "1", unit: "oz" },
      { name: "Sour Mix", amount: "1", unit: "oz" },
      { name: "Lemon-Lime Soda", amount: "splash" },
    ],
    instructions: [
      "Shake whiskey, peach schnapps, and sour mix with ice",
      "Strain into a shot glass",
      "Top with a splash of lemon-lime soda",
    ],
    glass: "Shot Glass",
    garnish: "None",
    baseSpirit: "whiskey",
    category: "shooter",
    difficulty: 1,
    strength: 3,
    tags: ["sweet", "party", "popular"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "shots",
    servingSize: "1 shot",
    proTips: ["Use fresh sour mix for better flavor", "Chill ingredients"],
  },
  {
    id: "drink-27",
    slug: "fireball-shot",
    name: "Fireball Shot",
    description: "A cinnamon whiskey shot with a spicy finish.",
    ingredients: [
      { name: "Cinnamon Whiskey", amount: "1.5", unit: "oz" },
    ],
    instructions: ["Pour into a chilled shot glass and serve"],
    glass: "Shot Glass",
    garnish: "None",
    baseSpirit: "whiskey",
    category: "shooter",
    difficulty: 1,
    strength: 4,
    tags: ["cinnamon", "quick", "spicy"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "shots",
    servingSize: "1 shot",
    proTips: ["Serve extra cold for a smoother sip", "Pair with apple slices"],
  },
  {
    id: "drink-28",
    slug: "vegas-bomb",
    name: "Vegas Bomb",
    description: "A fruity bomb shot with whiskey and energy drink.",
    ingredients: [
      { name: "Canadian Whisky", amount: "0.75", unit: "oz" },
      { name: "Peach Schnapps", amount: "0.75", unit: "oz" },
      { name: "Cranberry Juice", amount: "0.75", unit: "oz" },
      { name: "Energy Drink", amount: "4", unit: "oz" },
    ],
    instructions: [
      "Shake whiskey, schnapps, and cranberry with ice",
      "Strain into a shot glass",
      "Drop into a glass of energy drink and drink",
    ],
    glass: "Shot Glass",
    garnish: "None",
    baseSpirit: "whiskey",
    category: "shooter",
    difficulty: 2,
    strength: 4,
    tags: ["bomb", "party", "fruity"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "shots",
    servingSize: "1 bomb",
    proTips: ["Use chilled energy drink", "Keep the ratio 1:3 for balance"],
  },
  {
    id: "drink-29",
    slug: "washington-apple-shot",
    name: "Washington Apple",
    description: "A sweet apple shot with whiskey and cranberry.",
    ingredients: [
      { name: "Canadian Whisky", amount: "1", unit: "oz" },
      { name: "Sour Apple Schnapps", amount: "1", unit: "oz" },
      { name: "Cranberry Juice", amount: "1", unit: "oz" },
    ],
    instructions: [
      "Shake all ingredients with ice",
      "Strain into a shot glass",
    ],
    glass: "Shot Glass",
    garnish: "Apple slice",
    baseSpirit: "whiskey",
    category: "shooter",
    difficulty: 1,
    strength: 3,
    tags: ["apple", "sweet", "easy"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "shots",
    servingSize: "1 shot",
    proTips: ["Use tart cranberry for balance", "Serve ice-cold"],
  },
  {
    id: "drink-30",
    slug: "blue-kamikaze",
    name: "Blue Kamikaze",
    description: "A bright blue twist on the classic kamikaze.",
    ingredients: [
      { name: "Vodka", amount: "1", unit: "oz" },
      { name: "Blue Curacao", amount: "1", unit: "oz" },
      { name: "Lime Juice", amount: "1", unit: "oz" },
    ],
    instructions: [
      "Shake all ingredients with ice",
      "Strain into a chilled shot glass",
    ],
    glass: "Shot Glass",
    garnish: "Lime wheel",
    baseSpirit: "vodka",
    category: "shooter",
    difficulty: 1,
    strength: 4,
    tags: ["blue", "citrus", "vodka"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "shots",
    servingSize: "1 shot",
    proTips: ["Use fresh lime for best flavor", "Chill the glass"],
  },
  {
    id: "drink-31",
    slug: "irish-car-bomb",
    name: "Irish Car Bomb",
    description: "A stout beer bomb with Irish cream and whiskey.",
    ingredients: [
      { name: "Irish Whiskey", amount: "0.75", unit: "oz" },
      { name: "Irish Cream", amount: "0.75", unit: "oz" },
      { name: "Stout Beer", amount: "6", unit: "oz" },
    ],
    instructions: [
      "Fill a glass with stout",
      "Layer Irish cream over whiskey in a shot glass",
      "Drop into the stout and drink immediately",
    ],
    glass: "Shot Glass",
    garnish: "None",
    baseSpirit: "whiskey",
    category: "shooter",
    difficulty: 2,
    strength: 4,
    tags: ["bomb", "stout", "irish"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "shots",
    servingSize: "1 bomb",
    proTips: ["Drink quickly before it curdles", "Chill the stout"],
  },
  {
    id: "drink-32",
    slug: "pineapple-upside-down-shot",
    name: "Pineapple Upside Down Cake Shot",
    description: "A sweet pineapple shot that tastes like dessert.",
    ingredients: [
      { name: "Vanilla Vodka", amount: "1", unit: "oz" },
      { name: "Pineapple Juice", amount: "1", unit: "oz" },
      { name: "Grenadine", amount: "0.25", unit: "oz" },
    ],
    instructions: [
      "Shake vodka and pineapple juice with ice",
      "Strain into a shot glass",
      "Float grenadine for a layered look",
    ],
    glass: "Shot Glass",
    garnish: "Pineapple wedge",
    baseSpirit: "vodka",
    category: "shooter",
    difficulty: 1,
    strength: 3,
    tags: ["sweet", "dessert", "pineapple"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "shots",
    servingSize: "1 shot",
    proTips: ["Use vanilla vodka for cake flavor", "Pour grenadine slowly"],
  },
  {
    id: "drink-33",
    slug: "baby-guinness",
    name: "Baby Guinness",
    description: "A layered shot that looks like a mini pint.",
    ingredients: [
      { name: "Coffee Liqueur", amount: "0.75", unit: "oz" },
      { name: "Irish Cream", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Pour coffee liqueur into a shot glass",
      "Float Irish cream on top",
    ],
    glass: "Shot Glass",
    garnish: "None",
    baseSpirit: "various",
    category: "shooter",
    difficulty: 1,
    strength: 3,
    tags: ["layered", "coffee", "dessert"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "shots",
    servingSize: "1 shot",
    proTips: ["Pour slowly for a clean layer", "Serve chilled"],
  },
  {
    id: "drink-34",
    slug: "birthday-cake-shot",
    name: "Birthday Cake Shot",
    description: "A sweet, creamy shot with vanilla flavor.",
    ingredients: [
      { name: "Vanilla Vodka", amount: "1", unit: "oz" },
      { name: "Irish Cream", amount: "0.5", unit: "oz" },
      { name: "Amaretto", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Shake all ingredients with ice",
      "Strain into a shot glass",
      "Garnish with a sugar rim (optional)",
    ],
    glass: "Shot Glass",
    garnish: "Sugar rim",
    baseSpirit: "vodka",
    category: "shooter",
    difficulty: 2,
    strength: 3,
    tags: ["sweet", "dessert", "party"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "shots",
    servingSize: "1 shot",
    proTips: ["Use chilled ingredients for smooth texture", "Add a tiny splash of cream"],
  },
  {
    id: "drink-35",
    slug: "caramel-apple-shot",
    name: "Caramel Apple Shot",
    description: "A fall-inspired shot with apple and caramel notes.",
    ingredients: [
      { name: "Apple Vodka", amount: "1", unit: "oz" },
      { name: "Butterscotch Schnapps", amount: "1", unit: "oz" },
      { name: "Lemon Juice", amount: "0.25", unit: "oz" },
    ],
    instructions: [
      "Shake all ingredients with ice",
      "Strain into a shot glass",
      "Garnish with a tiny apple slice",
    ],
    glass: "Shot Glass",
    garnish: "Apple slice",
    baseSpirit: "vodka",
    category: "shooter",
    difficulty: 1,
    strength: 3,
    tags: ["apple", "caramel", "sweet"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "shots",
    servingSize: "1 shot",
    proTips: ["Add a cinnamon sugar rim", "Use chilled ingredients"],
  },

  // Punches (10)
  {
    id: "drink-36",
    slug: "jungle-juice-classic",
    name: "Jungle Juice (Classic)",
    description: "A crowd-sized party punch with vodka, rum, and fruit.",
    ingredients: [
      { name: "Vodka", amount: "12", unit: "oz" },
      { name: "White Rum", amount: "12", unit: "oz" },
      { name: "Orange Juice", amount: "4", unit: "cups" },
      { name: "Lemon-Lime Soda", amount: "4", unit: "cups" },
      { name: "Mixed Fruit", amount: "2", unit: "cups" },
    ],
    instructions: [
      "Combine spirits and juice in a punch bowl",
      "Add fruit and chill for 30 minutes",
      "Top with soda right before serving",
    ],
    glass: "Punch Bowl",
    garnish: "Mixed fruit",
    baseSpirit: "various",
    category: "party",
    difficulty: 1,
    strength: 4,
    tags: ["party", "batch", "fruit"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "punches",
    servingSize: "8-10 servings",
    proTips: ["Chill ingredients before mixing", "Use frozen fruit as ice"],
  },
  {
    id: "drink-38",
    slug: "jungle-juice-tropical",
    name: "Jungle Juice (Tropical)",
    description: "Tropical fruit punch with rum and pineapple.",
    ingredients: [
      { name: "Coconut Rum", amount: "12", unit: "oz" },
      { name: "White Rum", amount: "8", unit: "oz" },
      { name: "Pineapple Juice", amount: "4", unit: "cups" },
      { name: "Orange Juice", amount: "3", unit: "cups" },
      { name: "Lemon-Lime Soda", amount: "3", unit: "cups" },
    ],
    instructions: [
      "Combine rums and juices in a bowl",
      "Chill and top with soda before serving",
      "Garnish with pineapple and orange slices",
    ],
    glass: "Punch Bowl",
    garnish: "Pineapple wedges",
    baseSpirit: "rum",
    category: "party",
    difficulty: 1,
    strength: 4,
    tags: ["tropical", "rum", "batch"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "punches",
    servingSize: "8-10 servings",
    proTips: ["Add a splash of grenadine for color", "Use chilled soda"],
  },
  {
    id: "drink-39",
    slug: "jungle-juice-citrus",
    name: "Jungle Juice (Citrus)",
    description: "A bright citrus punch with vodka and citrus soda.",
    ingredients: [
      { name: "Vodka", amount: "12", unit: "oz" },
      { name: "Triple Sec", amount: "6", unit: "oz" },
      { name: "Lemonade", amount: "4", unit: "cups" },
      { name: "Orange Juice", amount: "3", unit: "cups" },
      { name: "Club Soda", amount: "3", unit: "cups" },
    ],
    instructions: [
      "Mix spirits and juices in a punch bowl",
      "Add soda just before serving",
      "Garnish with lemon and orange slices",
    ],
    glass: "Punch Bowl",
    garnish: "Citrus slices",
    baseSpirit: "vodka",
    category: "party",
    difficulty: 1,
    strength: 4,
    tags: ["citrus", "party", "batch"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "punches",
    servingSize: "8-10 servings",
    proTips: ["Use fresh lemonade if possible", "Add extra ice for large batches"],
  },
  {
    id: "drink-40",
    slug: "red-sangria",
    name: "Red Sangria",
    description: "Red wine punch with brandy and fresh fruit.",
    ingredients: [
      { name: "Red Wine", amount: "1", unit: "bottle" },
      { name: "Brandy", amount: "4", unit: "oz" },
      { name: "Orange Juice", amount: "1", unit: "cup" },
      { name: "Mixed Fruit", amount: "2", unit: "cups" },
      { name: "Lemon-Lime Soda", amount: "1", unit: "cup" },
    ],
    instructions: [
      "Combine wine, brandy, juice, and fruit in a pitcher",
      "Chill for at least 2 hours",
      "Add soda just before serving",
    ],
    glass: "Wine Glass",
    garnish: "Orange slices",
    baseSpirit: "brandy",
    category: "party",
    difficulty: 1,
    strength: 3,
    tags: ["wine", "fruit", "batch"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "punches",
    servingSize: "6-8 servings",
    proTips: ["Let the fruit soak overnight", "Use seasonal fruit for flavor"],
  },
  {
    id: "drink-41",
    slug: "white-sangria",
    name: "White Sangria",
    description: "Crisp white wine punch with citrus and stone fruit.",
    ingredients: [
      { name: "White Wine", amount: "1", unit: "bottle" },
      { name: "Peach Schnapps", amount: "4", unit: "oz" },
      { name: "Lemon Juice", amount: "0.5", unit: "cup" },
      { name: "Mixed Fruit", amount: "2", unit: "cups" },
      { name: "Club Soda", amount: "1", unit: "cup" },
    ],
    instructions: [
      "Combine wine, schnapps, and lemon juice in a pitcher",
      "Add fruit and chill for 2 hours",
      "Top with club soda before serving",
    ],
    glass: "Wine Glass",
    garnish: "Lemon slices",
    baseSpirit: "various",
    category: "party",
    difficulty: 1,
    strength: 3,
    tags: ["wine", "light", "fruit"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "punches",
    servingSize: "6-8 servings",
    proTips: ["Use chilled wine for faster prep", "Add berries for color"],
  },
  {
    id: "drink-42",
    slug: "fish-bowl",
    name: "Fish Bowl",
    description: "A fun party punch with blue curacao and rum.",
    ingredients: [
      { name: "White Rum", amount: "12", unit: "oz" },
      { name: "Vodka", amount: "6", unit: "oz" },
      { name: "Blue Curacao", amount: "4", unit: "oz" },
      { name: "Pineapple Juice", amount: "4", unit: "cups" },
      { name: "Lemon-Lime Soda", amount: "3", unit: "cups" },
    ],
    instructions: [
      "Combine spirits and juice in a punch bowl",
      "Top with soda and stir gently",
      "Add floating gummy fish for fun",
    ],
    glass: "Punch Bowl",
    garnish: "Gummy fish",
    baseSpirit: "various",
    category: "party",
    difficulty: 1,
    strength: 4,
    tags: ["blue", "party", "fun"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "punches",
    servingSize: "8-10 servings",
    proTips: ["Use clear soda to keep the color bright", "Chill ingredients"],
  },
  {
    id: "drink-43",
    slug: "party-punch",
    name: "Party Punch",
    description: "An easy crowd-pleasing punch with vodka and fruit juice.",
    ingredients: [
      { name: "Vodka", amount: "10", unit: "oz" },
      { name: "Fruit Punch", amount: "6", unit: "cups" },
      { name: "Orange Juice", amount: "2", unit: "cups" },
      { name: "Lemon-Lime Soda", amount: "2", unit: "cups" },
    ],
    instructions: [
      "Mix vodka and juices in a punch bowl",
      "Add soda just before serving",
      "Garnish with orange slices",
    ],
    glass: "Punch Bowl",
    garnish: "Orange slices",
    baseSpirit: "vodka",
    category: "party",
    difficulty: 1,
    strength: 3,
    tags: ["party", "easy", "batch"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "punches",
    servingSize: "8-10 servings",
    proTips: ["Use chilled juice to avoid extra ice", "Taste and adjust sweetness"],
  },
  {
    id: "drink-44",
    slug: "rum-punch",
    name: "Rum Punch",
    description: "Tropical rum punch with citrus and pineapple.",
    ingredients: [
      { name: "Dark Rum", amount: "10", unit: "oz" },
      { name: "Pineapple Juice", amount: "3", unit: "cups" },
      { name: "Orange Juice", amount: "2", unit: "cups" },
      { name: "Lime Juice", amount: "0.5", unit: "cup" },
      { name: "Grenadine", amount: "2", unit: "oz" },
    ],
    instructions: [
      "Combine all ingredients in a punch bowl",
      "Stir and chill for 30 minutes",
      "Serve over ice",
    ],
    glass: "Punch Bowl",
    garnish: "Pineapple wedges",
    baseSpirit: "rum",
    category: "party",
    difficulty: 1,
    strength: 4,
    tags: ["rum", "tropical", "batch"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "punches",
    servingSize: "8 servings",
    proTips: ["Add a float of dark rum for aroma", "Use fresh lime juice"],
  },
  {
    id: "drink-45",
    slug: "watermelon-punch",
    name: "Watermelon Punch",
    description: "A summer punch with fresh watermelon and vodka.",
    ingredients: [
      { name: "Vodka", amount: "10", unit: "oz" },
      { name: "Watermelon Juice", amount: "4", unit: "cups" },
      { name: "Lime Juice", amount: "0.5", unit: "cup" },
      { name: "Club Soda", amount: "2", unit: "cups" },
    ],
    instructions: [
      "Combine vodka, watermelon juice, and lime",
      "Chill for 1 hour",
      "Top with club soda before serving",
    ],
    glass: "Punch Bowl",
    garnish: "Watermelon cubes",
    baseSpirit: "vodka",
    category: "party",
    difficulty: 1,
    strength: 3,
    tags: ["watermelon", "summer", "batch"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "punches",
    servingSize: "8 servings",
    proTips: ["Blend and strain watermelon for smooth texture", "Add mint for freshness"],
  },
  {
    id: "drink-46",
    slug: "sparkling-citrus-punch",
    name: "Sparkling Citrus Punch",
    description: "A bubbly punch with citrus juice and sparkling wine.",
    ingredients: [
      { name: "Sparkling Wine", amount: "1", unit: "bottle" },
      { name: "Orange Juice", amount: "2", unit: "cups" },
      { name: "Lemon Juice", amount: "0.5", unit: "cup" },
      { name: "Simple Syrup", amount: "0.25", unit: "cup" },
      { name: "Club Soda", amount: "1", unit: "cup" },
    ],
    instructions: [
      "Mix juices and syrup in a punch bowl",
      "Add sparkling wine and club soda",
      "Stir gently and serve immediately",
    ],
    glass: "Punch Bowl",
    garnish: "Citrus wheels",
    baseSpirit: "various",
    category: "party",
    difficulty: 1,
    strength: 2,
    tags: ["sparkling", "citrus", "light"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "punches",
    servingSize: "8 servings",
    proTips: ["Keep bubbles cold until serving", "Use a dry sparkling wine"],
  },

  // Mocktails (5)
  {
    id: "drink-47",
    slug: "virgin-mojito",
    name: "Virgin Mojito",
    description: "A refreshing mint and lime mocktail with soda.",
    ingredients: [
      { name: "Lime Juice", amount: "0.75", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
      { name: "Mint Leaves", amount: "8", unit: "leaves" },
      { name: "Club Soda", amount: "4", unit: "oz" },
    ],
    instructions: [
      "Muddle mint with simple syrup",
      "Add lime juice and ice",
      "Top with club soda and stir",
      "Garnish with mint sprig",
    ],
    glass: "Highball Glass",
    garnish: "Mint sprig",
    baseSpirit: "none",
    category: "mocktail",
    difficulty: 1,
    strength: 1,
    tags: ["mocktail", "mint", "refreshing"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "mocktails",
    servingSize: "1 mocktail",
    proTips: ["Use plenty of ice", "Muddle gently to avoid bitterness"],
  },
  {
    id: "drink-48",
    slug: "shirley-temple",
    name: "Shirley Temple",
    description: "Classic sweet mocktail with grenadine and soda.",
    ingredients: [
      { name: "Ginger Ale", amount: "4", unit: "oz" },
      { name: "Lemon-Lime Soda", amount: "4", unit: "oz" },
      { name: "Grenadine", amount: "0.5", unit: "oz" },
    ],
    instructions: [
      "Fill a glass with ice",
      "Add ginger ale and lemon-lime soda",
      "Stir in grenadine",
      "Garnish with cherries",
    ],
    glass: "Highball Glass",
    garnish: "Cherries",
    baseSpirit: "none",
    category: "mocktail",
    difficulty: 1,
    strength: 1,
    tags: ["mocktail", "sweet", "classic"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "mocktails",
    servingSize: "1 mocktail",
    proTips: ["Add extra grenadine for deeper color", "Serve with a straw"],
  },
  {
    id: "drink-49",
    slug: "cucumber-mint-cooler",
    name: "Cucumber Mint Cooler",
    description: "A crisp, spa-like mocktail with cucumber and mint.",
    ingredients: [
      { name: "Cucumber", amount: "4", unit: "slices" },
      { name: "Mint Leaves", amount: "6", unit: "leaves" },
      { name: "Lime Juice", amount: "0.5", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
      { name: "Club Soda", amount: "4", unit: "oz" },
    ],
    instructions: [
      "Muddle cucumber and mint",
      "Add lime juice and syrup with ice",
      "Top with club soda and stir",
      "Garnish with cucumber ribbon",
    ],
    glass: "Highball Glass",
    garnish: "Cucumber ribbon",
    baseSpirit: "none",
    category: "mocktail",
    difficulty: 2,
    strength: 1,
    tags: ["mocktail", "cucumber", "refreshing"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "mocktails",
    servingSize: "1 mocktail",
    proTips: ["Use chilled soda", "Strain if you prefer less pulp"],
  },
  {
    id: "drink-50",
    slug: "pineapple-ginger-fizz",
    name: "Pineapple Ginger Fizz",
    description: "Tropical pineapple with a spicy ginger kick.",
    ingredients: [
      { name: "Pineapple Juice", amount: "3", unit: "oz" },
      { name: "Lime Juice", amount: "0.5", unit: "oz" },
      { name: "Ginger Beer", amount: "3", unit: "oz" },
    ],
    instructions: [
      "Fill a glass with ice",
      "Add pineapple and lime juice",
      "Top with ginger beer and stir",
      "Garnish with lime wedge",
    ],
    glass: "Highball Glass",
    garnish: "Lime wedge",
    baseSpirit: "none",
    category: "mocktail",
    difficulty: 1,
    strength: 1,
    tags: ["mocktail", "pineapple", "ginger"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "mocktails",
    servingSize: "1 mocktail",
    proTips: ["Use spicy ginger beer", "Chill juice before mixing"],
  },
  {
    id: "drink-51",
    slug: "berry-lemonade-spritz",
    name: "Berry Lemonade Spritz",
    description: "A berry-forward lemonade spritz with soda bubbles.",
    ingredients: [
      { name: "Lemonade", amount: "4", unit: "oz" },
      { name: "Mixed Berries", amount: "0.5", unit: "cup" },
      { name: "Club Soda", amount: "3", unit: "oz" },
    ],
    instructions: [
      "Muddle berries in a glass",
      "Add ice and lemonade",
      "Top with club soda and stir",
      "Garnish with berries",
    ],
    glass: "Highball Glass",
    garnish: "Mixed berries",
    baseSpirit: "none",
    category: "mocktail",
    difficulty: 1,
    strength: 1,
    tags: ["mocktail", "berries", "summer"],
    created_at: defaultDrinkTimestamp,
    categorySlug: "mocktails",
    servingSize: "1 mocktail",
    proTips: ["Use frozen berries for extra chill", "Adjust sweetness to taste"],
  },
];

export const drinkCategories: { slug: DrinkCategorySlug; name: string; description: string }[] = [
  {
    slug: "cocktails",
    name: "Cocktails",
    description: "Classic and modern cocktails with full recipes and pro tips.",
  },
  {
    slug: "shots",
    name: "Shots",
    description: "Quick, punchy shots for celebrations and party games.",
  },
  {
    slug: "punches",
    name: "Punches",
    description: "Batch-friendly punch recipes for groups and events.",
  },
  {
    slug: "mocktails",
    name: "Mocktails",
    description: "Non-alcoholic recipes that still feel festive.",
  },
];

export const getDrinkBySlug = (slug: string): DrinkRecipe | undefined =>
  drinks.find((drink) => drink.slug === slug);

export const getDrinksByCategory = (category: DrinkCategorySlug): DrinkRecipe[] =>
  drinks.filter((drink) => drink.categorySlug === category);
