export interface TvGame {
  slug: string;
  name: string;
  title: string;
  drinkRules: string[];
  shotRules: string[];
  episodeRecommendations: string[];
  created_at: string;
}

const defaultTvTimestamp = "2026-03-20";

export const tvGames: TvGame[] = [
  {
    slug: "the-office",
    name: "The Office",
    title: "The Office Drinking Game - Complete Rules",
    drinkRules: [
      "Jim looks at the camera",
      "Dwight mentions beet farming or Schrute Farms",
      "Michael says 'That's what she said'",
      "A character talks about pretzels",
      "Pam is working on art",
      "Angela judges someone",
      "Kevin talks about food",
      "Someone references the warehouse",
      "There is an awkward silence",
      "Someone says 'Dunder Mifflin'",
      "Andy breaks into song",
    ],
    shotRules: [
      "Michael declares bankruptcy",
      "A fire drill goes horribly wrong",
      "A surprise proposal happens",
    ],
    episodeRecommendations: [
      "Dinner Party (S4E9)",
      "The Injury (S2E12)",
      "Stress Relief (S5E14-15)",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "friends",
    name: "Friends",
    title: "Friends Drinking Game - Complete Rules",
    drinkRules: [
      "Someone says 'We were on a break'",
      "Ross mentions dinosaurs",
      "Joey says 'How you doin'",
      "Chandler makes a sarcastic joke",
      "Phoebe sings",
      "Monica cleans or organizes",
      "Rachel mentions fashion",
      "Central Perk couch shot",
      "Janice says 'Oh. My. God'",
      "Someone eats or talks about food",
    ],
    shotRules: [
      "A character gets engaged",
      "A Thanksgiving football game happens",
      "The gang dances in the opening credits",
    ],
    episodeRecommendations: [
      "The One With the Embryos (S4E12)",
      "The One With All the Thanksgivings (S5E8)",
      "The One Where Everybody Finds Out (S5E14)",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "how-i-met-your-mother",
    name: "How I Met Your Mother",
    title: "How I Met Your Mother Drinking Game - Complete Rules",
    drinkRules: [
      "Ted talks about destiny",
      "Barney says 'legendary'",
      "Marshall mentions Minnesota",
      "Lily gives a relationship rule",
      "Robin talks about Canada",
      "Someone visits MacLaren's",
      "A yellow umbrella reference",
      "Ted narrates from the future",
      "A slap bet is mentioned",
      "The group cheers with drinks",
    ],
    shotRules: [
      "Barney's playbook appears",
      "A slap bet slap happens",
      "The mother is teased but not shown",
    ],
    episodeRecommendations: [
      "Slap Bet (S2E9)",
      "The Pineapple Incident (S1E10)",
      "How Your Mother Met Me (S9E16)",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "game-of-thrones",
    name: "Game of Thrones",
    title: "Game of Thrones Drinking Game - Complete Rules",
    drinkRules: [
      "Someone says 'Winter is coming'",
      "A character dies",
      "A dragon appears",
      "Someone drinks wine on screen",
      "A sword is drawn",
      "A banner or house sigil is shown",
      "Someone says 'Your Grace'",
      "A raven message is delivered",
      "A betrayal happens",
      "A character says 'The North'",
    ],
    shotRules: [
      "A major character is executed",
      "A battle episode begins",
      "A white walker appears",
    ],
    episodeRecommendations: [
      "Blackwater (S2E9)",
      "The Red Wedding (S3E9)",
      "Hardhome (S5E8)",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "harry-potter",
    name: "Harry Potter (Movies)",
    title: "Harry Potter Drinking Game - Complete Rules",
    drinkRules: [
      "Someone says 'Harry'",
      "A spell is cast",
      "Hogwarts house points are mentioned",
      "The Golden Trio breaks a rule",
      "A character takes a train at King's Cross",
      "The Sorting Hat appears",
      "A house scarf is shown",
      "A magical creature appears",
      "Snape says 'Potter'",
      "A wand duel happens",
    ],
    shotRules: [
      "A major character dies",
      "A horcrux is destroyed",
      "Voldemort appears on screen",
    ],
    episodeRecommendations: [
      "Sorcerer's Stone",
      "Prisoner of Azkaban",
      "Deathly Hallows Part 2",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "parks-and-recreation",
    name: "Parks and Recreation",
    title: "Parks and Recreation Drinking Game - Complete Rules",
    drinkRules: [
      "Leslie mentions waffles",
      "Ron says he loves meat",
      "Tom mentions a brand name",
      "Andy does something dumb",
      "Donna says 'Treat Yo Self'",
      "Ben references Game of Thrones",
      "April shows no emotion",
      "Jerry makes a mistake",
      "A Pawnee mural appears",
      "Someone says 'Lil Sebastian'",
    ],
    shotRules: [
      "A campaign speech happens",
      "The group sings together",
      "A character gets engaged",
    ],
    episodeRecommendations: [
      "Flu Season (S3E2)",
      "Treat Yo Self (S4E7)",
      "The Fight (S3E13)",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "brooklyn-nine-nine",
    name: "Brooklyn Nine-Nine",
    title: "Brooklyn Nine-Nine Drinking Game - Complete Rules",
    drinkRules: [
      "Jake says 'Cool cool cool'",
      "Captain Holt is overly formal",
      "Rosa intimidates someone",
      "Amy mentions a binder",
      "Terry eats yogurt",
      "Gina dances or jokes",
      "A heist is mentioned",
      "Someone says 'Nine-Nine'",
      "Boyle says something awkward",
      "Scully or Hitchcock naps",
    ],
    shotRules: [
      "A Halloween heist begins",
      "Someone yells 'Title of your sex tape'",
      "An important case is solved",
    ],
    episodeRecommendations: [
      "Halloween (S1E6)",
      "The Box (S5E14)",
      "The Chopper (S2E4)",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "schitts-creek",
    name: "Schitt's Creek",
    title: "Schitt's Creek Drinking Game - Complete Rules",
    drinkRules: [
      "Alexis says 'Ew, David'",
      "Moira uses a weird word",
      "David panics about something small",
      "Johnny gives business advice",
      "Roland appears unexpectedly",
      "A character says 'fold in'",
      "The motel sign is shown",
      "Twyla mentions a wild story",
      "A wig changes",
      "A cafe scene happens",
    ],
    shotRules: [
      "A Rose family celebration happens",
      "A character performs on stage",
      "An engagement is announced",
    ],
    episodeRecommendations: [
      "The Fold (S2E13)",
      "Open Mic (S4E6)",
      "Happy Ending (S6E14)",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "new-girl",
    name: "New Girl",
    title: "New Girl Drinking Game - Complete Rules",
    drinkRules: [
      "Jess sings",
      "Nick says something grumpy",
      "Schmidt talks about being fancy",
      "Winston does something weird",
      "Cece calls Jess out",
      "The loft kitchen is shown",
      "A game (True American) is mentioned",
      "Schmidt yells 'Douchebag jar'",
      "A character says 'adorkable'",
      "Someone drinks a beer",
    ],
    shotRules: [
      "True American starts",
      "A wedding happens",
      "Someone gets fired",
    ],
    episodeRecommendations: [
      "True American (S1E20)",
      "Background Check (S4E6)",
      "Prince (S3E14)",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "rick-and-morty",
    name: "Rick and Morty",
    title: "Rick and Morty Drinking Game - Complete Rules",
    drinkRules: [
      "Rick burps mid-sentence",
      "Portal gun is used",
      "Morty panics",
      "A sci-fi gadget appears",
      "Someone says 'Wubba Lubba Dub-Dub'",
      "A universe is destroyed",
      "Beth drinks wine",
      "Jerry is insulted",
      "A timeline fractures",
      "The Council of Ricks appears",
    ],
    shotRules: [
      "Mr. Meeseeks shows up",
      "A character dies and respawns",
      "Rick says 'I'm pickle Rick'",
    ],
    episodeRecommendations: [
      "Pickle Rick (S3E3)",
      "Total Rickall (S2E4)",
      "The Ricklantis Mixup (S3E7)",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "its-always-sunny",
    name: "It's Always Sunny in Philadelphia",
    title: "It's Always Sunny in Philadelphia Drinking Game - Complete Rules",
    drinkRules: [
      "Someone says 'The Gang'",
      "Dennis gives a creepy speech",
      "Charlie sings or shouts",
      "Mac mentions being a badass",
      "Dee is insulted",
      "Frank pulls out cash",
      "A scheme is mentioned",
      "The bar is empty",
      "Someone says 'Wild card'",
      "A bird reference happens",
    ],
    shotRules: [
      "The gang gets arrested",
      "A musical episode begins",
      "A character sets something on fire",
    ],
    episodeRecommendations: [
      "The Nightman Cometh (S4E13)",
      "The Gang Hits the Road (S5E2)",
      "The Gang Buys a Boat (S6E3)",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "the-bachelor",
    name: "The Bachelor / Bachelorette",
    title: "The Bachelor Drinking Game - Complete Rules",
    drinkRules: [
      "Someone says 'here for the right reasons'",
      "A contestant cries",
      "A rose is given",
      "Someone mentions a 'journey'",
      "A dramatic pause before a decision",
      "A contestant interrupts a date",
      "A 'can I steal you?' moment",
      "A toast with champagne",
      "A limo arrival",
      "A confessional says 'connection'",
    ],
    shotRules: [
      "Two contestants fight",
      "A villain is called out",
      "Someone says 'my person'",
    ],
    episodeRecommendations: [
      "Season premieres",
      "Hometowns episodes",
      "Final rose ceremonies",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "succession",
    name: "Succession",
    title: "Succession Drinking Game - Complete Rules",
    drinkRules: [
      "Logan says 'fuck off'",
      "Someone mentions Waystar",
      "A power play happens",
      "Tom looks stressed",
      "Greg says 'uh' or 'um'",
      "Roman makes a crude joke",
      "Shiv rolls her eyes",
      "A board meeting is called",
      "Someone says 'optics'",
      "A luxury car appears",
    ],
    shotRules: [
      "A major betrayal happens",
      "Someone gets fired",
      "A shareholder vote is announced",
    ],
    episodeRecommendations: [
      "Nobody Is Ever Missing (S1E10)",
      "This Is Not for Tears (S2E10)",
      "America Decides (S4E8)",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "breaking-bad",
    name: "Breaking Bad",
    title: "Breaking Bad Drinking Game - Complete Rules",
    drinkRules: [
      "Walter says 'Jesse'",
      "Jesse says 'Yo'",
      "Someone wears a hazmat suit",
      "Blue meth is shown",
      "Someone says 'Mr. White'",
      "A desert scene happens",
      "Saul Goodman appears",
      "A lab scene happens",
      "Walter coughs",
      "A car wash reference",
    ],
    shotRules: [
      "A major character dies",
      "A huge explosion happens",
      "Walter says 'I am the one who knocks'",
    ],
    episodeRecommendations: [
      "Ozymandias (S5E14)",
      "Face Off (S4E13)",
      "Pilot (S1E1)",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "stranger-things",
    name: "Stranger Things",
    title: "Stranger Things Drinking Game - Complete Rules",
    drinkRules: [
      "The Upside Down is mentioned",
      "Eleven uses her powers",
      "Someone says 'Hawkins'",
      "A Demogorgon appears",
      "A walkie talkie is used",
      "Joyce panics",
      "A bike ride scene",
      "A Dungeons & Dragons reference",
      "A secret government scene",
      "Steve gives advice",
    ],
    shotRules: [
      "A major character is possessed",
      "Vecna appears",
      "A season finale battle begins",
    ],
    episodeRecommendations: [
      "The Upside Down (S1E8)",
      "The Battle of Starcourt (S3E8)",
      "Dear Billy (S4E4)",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "euphoria",
    name: "Euphoria",
    title: "Euphoria Drinking Game - Complete Rules",
    drinkRules: [
      "Rue narrates",
      "A slow-motion party scene",
      "Someone texts on screen",
      "A neon color wash appears",
      "Maddy says something iconic",
      "Nate looks intense",
      "A glitter makeup close-up",
      "A dramatic music cue",
      "A montage of memories",
      "Someone says 'Jules'",
    ],
    shotRules: [
      "A major confrontation happens",
      "A character relapses",
      "A big reveal happens",
    ],
    episodeRecommendations: [
      "Pilot (S1E1)",
      "Rue's Special (S1E8)",
      "Trying to Get to Heaven (S2E5)",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "ted-lasso",
    name: "Ted Lasso",
    title: "Ted Lasso Drinking Game - Complete Rules",
    drinkRules: [
      "Ted says 'Believe'",
      "A biscuit is mentioned",
      "Roy growls or curses",
      "Coach Beard gives a one-liner",
      "Rebecca shows vulnerability",
      "Nate looks anxious",
      "A soccer match begins",
      "A team chant starts",
      "Someone says 'football is life'",
      "A pub scene",
    ],
    shotRules: [
      "A big win happens",
      "A coach gives an emotional speech",
      "A major character quits",
    ],
    episodeRecommendations: [
      "Tan Lines (S1E5)",
      "Rainbow (S2E5)",
      "Sunflowers (S3E6)",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "lord-of-the-rings",
    name: "Lord of the Rings",
    title: "Lord of the Rings Drinking Game - Complete Rules",
    drinkRules: [
      "Someone says 'precious'",
      "A character says 'Mordor'",
      "A sword is drawn",
      "A hobbit eats",
      "A character says 'my lord'",
      "A ring appears on screen",
      "An elf speaks",
      "A horse charge happens",
      "A scenic landscape shot",
      "Gollum talks to himself",
    ],
    shotRules: [
      "A character dies heroically",
      "The ring is put on",
      "A major battle begins",
    ],
    episodeRecommendations: [
      "The Fellowship of the Ring",
      "The Two Towers",
      "The Return of the King",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "marvel-movies",
    name: "Marvel Movies",
    title: "Marvel Movies Drinking Game - Complete Rules",
    drinkRules: [
      "A superhero lands in a three-point pose",
      "Someone says 'Avengers'",
      "A quip lands after a serious moment",
      "A suit-up montage happens",
      "A shield or hammer is used",
      "A portal opens",
      "A character says 'I have a plan'",
      "A mid-fight banter moment",
      "A dramatic reveal",
      "A Stan Lee cameo (if applicable)",
    ],
    shotRules: [
      "A post-credit scene starts",
      "A major character dies",
      "A huge team-up moment",
    ],
    episodeRecommendations: [
      "The Avengers",
      "Guardians of the Galaxy",
      "Avengers: Infinity War",
    ],
    created_at: defaultTvTimestamp,
  },
  {
    slug: "star-wars",
    name: "Star Wars",
    title: "Star Wars Drinking Game - Complete Rules",
    drinkRules: [
      "Someone says 'The Force'",
      "A lightsaber ignites",
      "A droid beeps",
      "A planet name is mentioned",
      "Stormtroopers miss a shot",
      "A character says 'I have a bad feeling'",
      "A ship jumps to hyperspace",
      "A cantina or bar scene",
      "A character says 'Jedi'",
      "A helmet is removed",
    ],
    shotRules: [
      "Duel of the Fates begins",
      "A major character dies",
      "The Death Star fires",
    ],
    episodeRecommendations: [
      "A New Hope",
      "The Empire Strikes Back",
      "The Force Awakens",
    ],
    created_at: defaultTvTimestamp,
  },
];

export const getTvGameBySlug = (slug: string) => tvGames.find((game) => game.slug === slug);
